---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linux-config-v1
  namespace: media
  labels:
    app.kubernetes.io/name: &name linux
    app.kubernetes.io/instance: *name
  # snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 15Gi

  storageClassName: ceph-block
