# Alternatively: https://hub.docker.com/r/linuxserver/rdesktop
# Also: https://hub.docker.com/r/linuxserver/blender
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linux
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: lscr.io/linuxserver/webtop
      # https://github.com/linuxserver/docker-webtop#version-tags
      tag: ubuntu-kde
      pullPolicy: IfNotPresent
    # https://github.com/linuxserver/docker-webtop
    env:
      TZ: "${TIMEZONE}"
      PUID: 0
      PGID: 0
      SUBFOLDER: /
      KEYBOARD: en-us-qwerty
      TITLE: desktop
    service:
      main:
        ports:
          http:
            port: 3000
    securityContext:
      seccompProfile:
        type: Unconfined
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: linux-config-v1
        subPath: webtop
      shm:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
        mountPath: /dev/shm
      dri:
        enabled: true
        type: hostPath
        mountPath: /dev/dri
        hostPath: /dev/dri
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
#        cert-manager.io/cluster-issuer: "letsencrypt-production"
#        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
#         auth.brent.arpa/enabled: "true"
#         auth.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: desktop
        hosts:
          - host: &host "linux.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
#            secretName: "linux-tls"
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
