---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tubearchivist
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tubearchivist-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # TA_PASSWORD, ELASTIC_PASSWORD
        key: tubearchivist
