---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tubearchivist-nfs
spec:
  storageClassName: tubearchivist-nfs
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.109.29
    path: /volume1/Media//TubeArchivist
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tubearchivist-nfs
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: tubearchivist-nfs
  resources:
    requests:
      storage: 1Mi # Size does not matter
