apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:W3d3U51k/gM=,iv:KOZFXjHGxBsujXs10gm3Jvt42tIQXFjNhD6ZRXsZQcY=,tag:qsHE6V9zoasTdMb4iu2Xbg==,type:str]
    password: ENC[AES256_GCM,data:7T4OiFwl0Xg=,iv:HzBovlmwCV8d2o/8FevYYMLxIDeFmKapmarT+8nIGgA=,tag:P0Lgtizr+Ml2NJw8+Wuy2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZ05TM1cwTTBxT1FKUGI3
            cnIxMmdqZDdESWIvT3UvaEVUNCtXZStnNndRCm5lVitoQW1lWVZ3OWhYNDdqRFcz
            enMxTGdTWUswUytmdk1NRmFvbW9pWm8KLS0tIGgwU2Q4NHhTREp3YStHS0xsc1E0
            SnV1Z0gyS0hnQ1dQZStBUmdNejFueE0KZAgxD+EwMmzDuvVo3YGl97oU4Dp4YB9v
            vWnsYnCMs5DVFPJhl0AjC1oZPv1LED8my7l1V7GIjl4DFOPZ+5rVAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-30T06:35:15Z"
    mac: ENC[AES256_GCM,data:so7+jVuUnEJHZYjReQSxA+h+WLR65p26ZhYcBMp5QFmeU2ewI0mdQIPJIcV/QnNJyH0xBEL4mo+8Hkvnf2qWzDJ3SNpcJtNnVcmmsvPdF4/N4Y7GPCoj+0wHEq8mRz/0Crwldpikk6j2RCNzRAW9nbqAneqayBWxVs549Ox3uKI=,iv:NRQlrLcel/c3g67wu5MGzVo6F5q6lwCI4KE/D13PkD0=,tag:PbGuCj6lH1yUflDKJGEKHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:LR8srm7OEFX8rqI065gaFg==,iv:mjBganoP0/TQ98ha7zyVaDVa9yfstCqO9eLTp7n6FVA=,tag:zWKlc7EVFXk/srCioh3mIg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:ZvpSy3IqnGYblQn3TEkiwP8xU+OiJ7TErm3rr83i7G8=,iv:DhbCF5HgmcRL2miPjwWmkVJxu7hSQQjV2kW0SOnxCLU=,tag:PnqSMP1vPrABvUJN0vpWzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZ05TM1cwTTBxT1FKUGI3
            cnIxMmdqZDdESWIvT3UvaEVUNCtXZStnNndRCm5lVitoQW1lWVZ3OWhYNDdqRFcz
            enMxTGdTWUswUytmdk1NRmFvbW9pWm8KLS0tIGgwU2Q4NHhTREp3YStHS0xsc1E0
            SnV1Z0gyS0hnQ1dQZStBUmdNejFueE0KZAgxD+EwMmzDuvVo3YGl97oU4Dp4YB9v
            vWnsYnCMs5DVFPJhl0AjC1oZPv1LED8my7l1V7GIjl4DFOPZ+5rVAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-30T06:35:15Z"
    mac: ENC[AES256_GCM,data:so7+jVuUnEJHZYjReQSxA+h+WLR65p26ZhYcBMp5QFmeU2ewI0mdQIPJIcV/QnNJyH0xBEL4mo+8Hkvnf2qWzDJ3SNpcJtNnVcmmsvPdF4/N4Y7GPCoj+0wHEq8mRz/0Crwldpikk6j2RCNzRAW9nbqAneqayBWxVs549Ox3uKI=,iv:NRQlrLcel/c3g67wu5MGzVo6F5q6lwCI4KE/D13PkD0=,tag:PbGuCj6lH1yUflDKJGEKHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
