---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: onepassword-connect
      namespace: external-secrets
    - name: nginx-external
      namespace: networking
    - name: authelia
      namespace: security
    - name: rook-ceph-cluster
      namespace: rook-ceph

  values:
    main:
      type: deployment
      annotations:
        reloader.stakater.com/auto: "true"

      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          fsGroup: 568
          fsGroupChangePolicy: "OnRootMismatch"
      containers:
        main:
          image:
            repository: ghcr.io/sct/overseerr
            tag: 1.33.2
          env:
            LOG_LEVEL: "info"
            PORT: &port 80
          resources:
            requests:
              cpu: 15m
              memory: 226M
            limits:
              memory: 1937M
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: "internal"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:eye-circle
        hosts:
          - host: &host "overseerr.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config-v1
        mountPath: /app/config
