ansible_become_pass: ENC[AES256_GCM,data:VnFoQS/00J4=,iv:PnYScpd5C1j8w1MQgRz9dlqrbTeDNaON0bNFPkK/CCA=,tag:greIBHh5T9UqLS9xhAlkuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Y2xuMW9WN3BFNThIQXdw
            bXZMQTUvTHVMazZsTWZTeGFuc3lBeTNORUdrCk02ZjkyT0JqeFJtQm4rL2JVU2pn
            Wm5oYzBCeW1sNFR6dTlnY0NobEl1NEkKLS0tIHRic3VkU3pVazgyd2pZdTk5M2JC
            c0VWVlc1TmROcVZPOXpnTWx0THFITE0K9tKDb+OWElREPssNgLpag+xEEZW9njGM
            dpPaEaCUvOeY5zOizA7XZGOni/icH0bhl/7CRHxV0OTdiGRm1M5qGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T23:54:22Z"
    mac: ENC[AES256_GCM,data:Qc8EuGMjU03ZySnFmwUMs9/foMh775OKVRkvrDMUbVRWerZ5cXDwaOfjrzWN78aIjiE7mszLpuiJCGpEL/Btwm4eWWGVkaXYGCmPnmkwe2fjkNUHH4CiCrYekfV9DM07VDaOwSW47xtjEPkBDWb1KCFQ5l1A1bMnrxNAEjiUSH0=,iv:xYtNkJpVvMeQca2VJ5CWHld3SCzL6DFVBytmpUUym6c=,tag:RbWmTZftbXUdyWmGy0FWLw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
