ansible_become_pass: ENC[AES256_GCM,data:jRyydQCcLeQ=,iv:UvEfRXoi17LeUg3QeiYrymt/ORu24HXtSMZPdlbajkM=,tag:FsGzhgMer8TpW0Kynd15XQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYkpnSWY0Mjh2Y2RtU2R0
            OHhPWWtRRnIwTXNqY3NBMWYxMzU3czZWbG13CnZGbVFvVEVNQ1hEaGNqQVI0TERn
            S3Z4YXFJMm1qRHB6Y1JQcTl4Wm5aYVUKLS0tIHM4Wi90dnFqWU12eGlvcUU5NDJ6
            V2luQmJZVkJ6QllzaFY3L21OWDlzbm8KH78Al4WI969dfoFGtxMtUh4xzoeqCC3o
            j8z/fUIBT1UFCKZalCjHwhY13uAjkAMtJlWwYDKXcynHnUpZYRKdBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T21:52:43Z"
    mac: ENC[AES256_GCM,data:LzvaMxHqoxHK0lZDfQD6aI7bw10jyEJpIUq1uVT5bICUKVDss5pwDA8FM2Znk7AzllkOXmC7pNP0uC4Td3CZTL4u8n+eK4TFjo4wTRbBgJcfmWfpfCx47kgYdKQslfkw/2FUNgTvmKT+5VCgE0E/XvtYPzXRNzIuQet2QGrTIFE=,iv:Typm1ulE5vtQfuYeHohi2sNSkdvJHtK6NN/yZ2jbi3w=,tag:9GZZbMV1WwX8NsjD1kIBKg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
