ansible_become_pass: ENC[AES256_GCM,data:NKWdo9Fa3sA=,iv:n24tQ3/zo2WEsJLCQxw/y5C8wYmTrKglg6RqT3CImEg=,tag:Mo1NqnSTXCWM7NL08yGzFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteGxRUWM2Y0ZYQXBzSVBl
            NjdWNVNzMlBvbWQ1c3I0QWlmclNZOWRYSEVJCjJjYVdmSDhLYlVvNllURmpJT0Zj
            VnZuc2RQMElVMVVrVGFNeUZheWh2dGMKLS0tIE93NXR5VHlDQjRZb1dhK0JNdjVM
            SlNscWwrQ0xvQm5MZjJUTEE1L1l1TncKPrLNclMjJqfLAj4bYEHi1xVgswgqCPGD
            idIiafwpEDr5FpBOvQwK7uxiozY1ZAO5bKDTfWLEYrs9aKtfZQOO6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T20:24:43Z"
    mac: ENC[AES256_GCM,data:COVWsl4EZmfIxpH0ru6fKEGAhplGadp/aSsVtnWPlJGHPiy+FMxpFEjAE2bgLZFyBmgWWdj4l6kQbM8YKPWgESxZzPmkyPGd8DOTIBz2+frqsPmOkuhhokJGU0apIlNTxkjraIN45v1NkjoLWgChlJnUz2PbPkJ+f4Kx3pkRwiA=,iv:IOHAngiZDI+AWfQIKQ7mpSfUzHmKZ2XFbFXoEXx+QIw=,tag:ZC5ElKBJ+2WJ8blFlyJRbA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
