ansible_become_pass: ENC[AES256_GCM,data:WCSBw/rLrsg=,iv:s6/YyMFcUo7PiU8Gd9EOWmVuQ42Te/IEPKJeJgraSao=,tag:LIorjVVhiAn/ooEOyU2V/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnd3RKY2lPbWtnUldidFlm
            YWVsOHlPU3RCNmtlekRIMWtYZ0RxYkVnbXo0CjBIbjVZREJUOXRhTVJtWmdjOFdG
            N28ySUVka0Y1Rml5bHVuUUV6Y2h1V2cKLS0tIDZEYk0wWTdySWtIYWpieDVBR1VR
            UjB1Qis4Q2VjRUd6eGhnNDdLVlNnbEEKRlEbQYRNY3dkoXI8St+YJeQzUGKIkUMf
            n7AxAAnH1yBaz1JzEOCh93vLNAqUXsO/x4CA7EZWqhu+lbDQsuczCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-12T00:11:40Z"
    mac: ENC[AES256_GCM,data:uXUbOTwLiELwwsR4uZO1Ab6fGslWqFMlBcLnfunfG2KhS4cv62+FRsdY5ezQOksDxwjkLkyTvVm2QnzEyfq9lcKLpDYEoGeQkYEMx+DVwHUYnNJdlx89rj2ZfRKi1yc6Vi9ftiwqTPc2cjrdatPG0+q9Z70Y2dB1RpWBlRkhiZI=,iv:zKul15Jglr38IoEdrpUIwmnBolJ/mOYKJ2Zr7QvkvTs=,tag:6nzM84xpJPFb8LL4HhqZ/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
