ansible_become_pass: ENC[AES256_GCM,data:vmjWlBHYngo=,iv:kujNbh1pTBifC6MtpO11VidJHooej6sL/Z1H0yaCXGo=,tag:PXZahrQJm3MhJ9vQWVSLFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNmJqNWZhUFRVd01FR2Vo
            LzJzZ2FiZlNneEFaMEo5QXpzNDFielVjZVFJCnpET0tTRDV3TkQyemxMaTVGRFo1
            c2pJbVpsTGUwaG00eVBDR0hCeEpqUnMKLS0tIE9IRUU0cUZ4dDF3VU15ZndmMkJj
            ODgxeUpGeUxvSWV5RVBJVDJFNjQ1cEEK+oA2e52+TibUsEUOPdeVyEwYJ5AV+y0O
            Gl66IBiRuNsSpagQJGm/R5ZRu0IkTvRoCHQ5F1tko8H4seJEuDTTKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T20:08:41Z"
    mac: ENC[AES256_GCM,data:R0IQ+wVOXa2rxO5DgdCAY7FIugYtZ/IUYD6Y++QuT93pjiBvnCrlWFQ3iOiewF6sOJq/NA+tSTUWoNduEH6QkEzpzGlN4lvawMIEckPiBzYII8dFjjr9CvxM2AeTr49gz16vckuWjypza777GHhLjq2s5tNYNcAGaYAB5FwrXuQ=,iv:IaoMe8nBkgNOJN5EQ2kRjYYoRV4Z65e1/Uxy1Sl+Ez0=,tag:AB81kF7oYCjzdO6DBY5cjA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
