ansible_become_pass: ENC[AES256_GCM,data:s67b+x9jHjc=,iv:1+becr7sqmBwNI31AWiT7qMjLR+hjnFbglZu7jhGxOk=,tag:pSUmDGTIKnyvvzhcaQe98Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYmRPU0tSK3c0OVhWeEYy
            allxRk8vOUFUdHpjaGluWkhVWTcvZHNoZVVZCjNmYityUmZWWkdqcUVsc01UUml3
            OXlJdXBKQ3llbTlBS3p5czZrOFV6M1kKLS0tIEkxZGZWQm5ob3lncFkvMEdtZmZJ
            N2FENTNSMnhZSjUxUHNmS0N2OU9kUUEKH0ouWqdXehBYTKIbSZcOQl0tFeb+HSMl
            B6W8WjbW8XMik+0c6dCBv23orxw0FiHJjQOVox9cAggOXbmsfk1jxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-12T00:11:40Z"
    mac: ENC[AES256_GCM,data:FIKQ0OUU8UOciEvKkcBI7NTAeXWH5CIezWBczw7Pua2gxw5ggsCgQPwKChtpDOJI+0ZR9pGaiM00shxoEy0DsOmot/kUgK3tmhcH6qblCFr6rV3GJcgNAGx4u0K8/z+oHbIoCtVZJ0u/DGDoAlfSBEL1rLlOEgI2VJO2oE/j+b0=,iv:C26NLM3kJvRYlWJyfV5dxp+DtENmgDrEYz+7PPoOfN0=,tag:XejTSI9mbRFA7hBxz21OrA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
