---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tubearchivist
  namespace: flux-system
spec:
  interval: 2h
  url: https://insuusvenerati.github.io/helm-charts/
