---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: goldilocks
spec:
  interval: 5m
  chart:
    spec:
      chart: goldilocks
      version: 7.1.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      resources:
        requests:
          cpu: 15m
          memory: 145M
        limits:
          memory: 174M
    vpa:
      enabled: false
    dashboard:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/appName: "goldilocks"
          hajimari.io/icon: "abacus"
        hosts:
          - host: &host "goldilocks.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: ImplementationSpecific
        tls:
          - hosts:
              - *host
            secretName: "goldilocks-tls"
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          memory: 64M
