apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:+wIRVBgOgA0=,iv:uRFXJLyEe2uNS2WGYhhRaJD70cM/D4xVoONYUAh2wmA=,tag:c5HM0xQPTGr3i+9iILVApw==,type:str]
    admin-user: ENC[AES256_GCM,data:m5pZe2o=,iv:I7iUGkBBmMrLuwQ1YNvB9LXb7Y8KRnr+C6ucxqMXWSI=,tag:QnkeMc76cew692XdwEwnhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOXUyMW1xVTJaZSttakdO
            VUpXTG0yTjhxSzV6T29KTVMvNlpyMisyNmhjCkdVMHBiVFZ1L2Z0c1dIeG1RQXIr
            S0h0MVpxSEhYUnZ4L0NxNDRjR1hxL1EKLS0tIHBNQTRUUHAwVmdtT05vT0VPbDdm
            V2FzelJGekM4bDF1ZUc5N204RkFtencK2/9M1Bem+bx0E2QFAnM6ztEljg85G9Yx
            rs26gUrWnsmjv9PXi275Bg+mLMmTruyXnZi1WcphdSbP7wMWN46CDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T19:33:40Z"
    mac: ENC[AES256_GCM,data:Kct0POUWoYChg/HO2coFRWbCrfZ0+0IENXcEAiXdv6AVgMqKTQN9+X6XQQzuS5m3Nw3RrADtxZS7Ztvc35LxQFqdvbSW30wx24X94DK7EpWTMtAxm0MO5q+9nwf102zLF3f20iRK1VhtXjg9TFzCC3csHlf+wAPYKiN7WGBi2fc=,iv:n5DBerax14qi2PP+4MLl2qFKOW9lFGZkQzNpx/JPzs4=,tag:uBXoDSPaQRTZ+5IolHRsNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
