apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:9gSF6rnDcOA=,iv:Tzwju3k0+JOfXeYhscBXKb5kAKOy+VLOYCaqF02WiNY=,tag:2SqWL5qMrPrvs13bKYo9rQ==,type:str]
    admin-user: ENC[AES256_GCM,data:R488MUM=,iv:lhm6lFsePho2XyGT5+tD/M0JJwwBZljJ+u5LjBOteL4=,tag:L+9R5poJMThstBSqHPI07w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbU5lUlp3SVpKL3BVNVJr
            WUZGN3N5eENMdlJGeDAva1JrWG5qR25JVlJjClJTc0NTMmEvNDJhUkRHRGk2Z2VG
            elZ2MnNocmYyUVdoY0hsaXN4dEZ4OUkKLS0tIDVzRFdQWWZCaE15L2RpZVZURVph
            SWNEN1BGNHRHZmxmbXk2dlp4aUQ3YTQKVuW6LSBn1quZhd3ok0ObmcnRoKlczwzQ
            ul2xQ7Ic4s5sRGtpdotJ1mN8GAGg6C1XJkrnIxTEt3UHRimH70ypag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T21:54:05Z"
    mac: ENC[AES256_GCM,data:TASp0YbpgXaVgsCOR5YwhDZgE/uZ1nfBlUKWRteyhEJd153Vhtx533Fn5HUweI15KDRCrR9VTOVTdj/WilqsTAvI+Ryt5I8ljqYxC9Xqk7XS7CPiMhlu78aNbz2AMKniRBHEGKXVZBdPSWihJ7CtsOVF1crhgaDHaeLsQsobUUk=,iv:iah1oAq0L5LOhNazDo4b2hvjo8vzOlQGt9+TgEtTJCg=,tag:zlAu6xcybBXrWUcpcSzNog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
