apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:a45KYgzD7tVhin7KN3EQ30NGzrVh+WDK,iv:gGW0Ty1biyTI1dvrnWFW8dRkmp6DK9baTOiXKdOy8cE=,tag:Ik+DeF1NyenGBSo44OutEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRGg5QkdHSnNDdE05MG5G
            S0E1VGcvWFdSanhLWE1iem5jMmU0dHJ0NXhRCmtCS0J6Q01BYXBkc0hMcDU4RU9Q
            NEhaMHc1LzdKdzZJaHZER2U3RFBwYm8KLS0tIGl6OTRUYWJuMXJZQzVXcjQ3enVl
            VTNLMHFXL3E2Y2dydDl0R3QyOVZORG8Kyo1ZVmoZQXXBZ9dnaLCZtQP2xDSovKUA
            wX8sWDP11YXaxgMuRVaZq0ysmHnXJ8BtTMUOTYNi+3dkEkO9rvtIAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T20:26:00Z"
    mac: ENC[AES256_GCM,data:qZQajKq6P1mNBUMj1soHZb9eohktRO8F6Pvjz8/HbdP01kgu0wIFQl+tpJI4WE62eMHd2644WS9Ib8u2WjJqClMzzAJ646fAjzD8/kmn8+GTWyb86SNZ8R6e9dB8sXEuKSNmO49QllYrSX0TNpsW13BHxcPwR8lTsORnt4tRqyw=,iv:+swrDkRfJEO9QF2TCVgziHBYBhg74F3ApGvtbL1fgq4=,tag:xf9Z4twd9fUzMvjB8D0Rng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
