---
---
authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 1m
  ldap:
    address: ldap://10.0.103.10:389
    implementation: activedirectory
    timeout: 5s
    start_tls: false
    base_dn: dc=bharris,dc=co
    additional_users_dn: ou=Users
    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectCategory=person)(objectClass=user)(!userAccountControl:1.2.840.113556.1.4.803:=2)(!pwdLastSet=0))
    additional_groups_dn: ou=groups
    groups_filter: (&(member:1.2.840.113556.1.4.1941:={dn})(objectClass=group)(objectCategory=group))
    group_search_mode: filter
    user: CN=Administrator,CN=Users,DC=bharris,DC=co
    password: password
    attributes:
      username: sAMAccountName
      display_name: displayName
      mail: mail
      member_of: memberOf
      group_name: cn
session:
  redis:
    high_availability:
      sentinel_name: redis-master
      nodes:
        - host: redis-node-0.redis-headless.databases.svc.cluster.local
          port: 26379
        - host: redis-node-1.redis-headless.databases.svc.cluster.local
          port: 26379
        - host: redis-node-2.redis-headless.databases.svc.cluster.local
          port: 26379
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: bharris_session
      domain: bharris.co
      authelia_url: https://auth.bharris.co
      default_redirection_url: https://bharris.co

notifier:
  disable_startup_check: true
  smtp:
    address: smtp.gmai.com:587
    sender: Authelia <bh2754@gmail.com  >
    disable_require_tls: true

totp:
  disable: false
  issuer: authelia.com

webauthn:
  disable: true

duo_api:
  disable: true

access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks: ["192.168.15.0/24", "10.0.0.0/16", "192.168.50.0/24"]
  rules:
    - domain: ["grafana.${SECERT_DOMAIN}"]
      policy: bypass
    - domain: ["abs.${SECERT_DOMAIN}"]
      policy: bypass
    - policy: bypass
      domain: ["*.${SECRET_DOMAIN}"]
      networks:
        - internal

identity_providers:
  oidc:
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: grafana
        description: Grafana
        secret: "${SECRET_GRAFANA_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes:
          - openid
          - profile
          - groups
          - email
        redirect_uris:
          - "https://grafana.${SECRET_DOMAIN}/login/generic_oauth"
        userinfo_signing_algorithm: none
