apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:GoDideWdxF28YUNF4l/iTuCJtvsOakBgYuWWTv8mrnTrx6s7PubPBw==,iv:359f/9LecUhOA07dfuDmQW3y3qgeuRgGGEryl0dYtxI=,tag:wbqilNYgGatLyAK7YPjkhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRclo0U1lSZzd0UGY5bEtq
            RkZvb2QyNUhzc0c0ZDNhQTNrMGM4ZGllYVdjCnBjNHhUaFB3ekNJcUZrWVR4cXA1
            OURjbmNZanp2OFVscWRsOFp5dmZGS2MKLS0tIGRLZGV0blB1OW9aZDI3TUVHWTN6
            V2tiR0MxUGRhWGtQVitQWWVOS0VMZG8K7y4nADM5AtBmGbb+ooKXkJ9ZlybWE1x7
            Zxx9mS7a4FI8Rqh1+F3rin7MVEVjIduIrqP/ZFgpEDb+dWtbZFdQzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T19:33:33Z"
    mac: ENC[AES256_GCM,data:an+1Px6UClusmZ4fDe86iXfZsICrrAwLbwM6rKU4iimeXnDA408CKAsQkPNUimilc2vYpna/AiB+NYLoWzrT5Q6ZUVj54xBBXM4bZ4ztS6ktq7eEi9iBjxJlv83rM5Q+I5o82OSilyBj4wRWPDxvSwhEjsste3G3AAzMnKdDtVQ=,iv:GLV7h2p42QEpqoapIMTjA7hRA0JmjIp0iJnJdkhc2j8=,tag:U+pGVU/vJ90V4IvldU7z9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
