apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:Pws9v/XJ9VAcibArtXYiTAkAJLwEmaA2iFECB76K+mIMd/KfaiY6eQ==,iv:eXFYlefoC6LsKr5Ehp22ZvYbLhAxnZgvVok5Kz+QxoU=,tag:KZQRi2cVmy84Em6i0OMaIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcEJBRHdrUjhyRW1jOTZL
            aUZUQWIxdFFONkxaVkFaTC9oUEhaMzIzbjBjCndsWWpYaUIxekxJVFE2RG5WaGJh
            T0syNEZTYU9hL0xHOEtCZTNTU3NOekUKLS0tIGJKQTNsc292WG5Jb1Z0OU9aanF5
            Tlp1Q214OVQ3Z1JlSkRHYkkyTUZNcjAKxUPzQQz7ZQiZf3dSUZ0rS2I1u2asLH/x
            uhWBuYe48tjOhZcG/98y8KB83M8K7B5PAp/Ma8FZ8iBi9vo3IvrNyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T20:09:57Z"
    mac: ENC[AES256_GCM,data:oq4rZIQlAebnqPqe9WFZrcVI2bck/bzaHKI4a5GEDYRupFdwrWxumRW6gxHItfnHnr0UTEuQzpJeGi5HlSUiOecgc/6P677IvVE22b4EHSv87pCF59cxFMvYVJu1Xj/0S9+LKYJC/PaQLyNmjWNyjFMl0tsTxUGC14PwL/KYTNk=,iv:LJBMQGsDDDlvEc5kEoL+rNORQfa4AIbLjltutH4Eb30=,tag:hDH3L7mTUwJg20Oom2mHjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
