---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app komga
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
#     version: 2.0.1
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:

    controller:
      type: deployment


    image:
      repository: ghcr.io/cbc02009/komga
      tag: 1.7.0@sha256:da48a020dc6ba06d9334cf82ee4f8e2771d57e0395897a22508d013593c2f405

    env:
      KOMGA_CONFIGDIR: "/config"
      SERVER_PORT: &port 8443

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-box"
          hajimari.io/appName: komga
        hosts:
          - host: &host "komga.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: komga-config-v1

      media:
        enabled: true
        type: nfs
        server: "10.0.109.29"
        path: /volume1/Media/comics
#       mountPath: /media
