---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vector-aggregator
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vector-aggregator-secret
    creationPolicy: Owner
  data:
    - secretKey: GEOIPUPDATE_ACCOUNT_ID
      remoteRef:
        key: vector-aggregator
        property: GEOIPUPDATE_ACCOUNT_ID
    - secretKey: GEOIPUPDATE_LICENSE_KEY
      remoteRef:
        key: vector-aggregator
        property: GEOIPUPDATE_ACCOUNT_KEY
