---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vector-aggregator
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vector-aggregator-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GEOIPUPDATE_ACCOUNT_ID: "{{ .GEOIPUPDATE_ACCOUNT_ID }}"
        GEOIPUPDATE_LICENSE_KEY: "{{ .GEOIPUPDATE_ACCOUNT_KEY }}"
  dataFrom:
    - extract:
        key: vector-aggregator
