---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: varken-config-v1
  namespace: media
  labels:
  # snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: varken
    app.kubernetes.io/instance: varken
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
