---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ombi
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/ombi
              tag: 4.43.5
            env:
              PUID: "1000"
              PGID: "1000"
            resources:
              requests:
                cpu: 15m
                memory: 273Mi
              limits:
                memory: 292Mi
    service:
      main:
        ports:
          http:
            port: 3579
    ingress:
      main:
        enabled: true
        primary: true
        className: internal
        hosts:
          - host: &host ombi.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: ombi-config-v1
        globalMounts:
          - path: /config
