# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:/5dG0CzQpMZ8Vn6KQ/rRS9xIxQfyZqmsYyaoeRlemlWYzQ90zIY51IASbWXumjjszk0aVrLFtnmVhFwQ4+hxOUX21pduRuP1oV+XNTKCApuDwpU7YbVopHmC9l6a3DhzbiML/AFdHT3MF5V2yLKYJ6F0oTPmNDWR6B87RRfhFqVArnmFs9Ne2bhKeu/YlB8LsvYZH3P0xOqKafA0twkWh3Sb/XoNbEGqBPQHstMUJSrcK6+By+dOxcx50xWv9KJZxu6xMClrLUJELVdvWw9Cv54vyIHlLmcsnzwRONwKUPmg7fCVm/dk36vKhAEfGpPxtUcZb3Lngtx+B5gTCR1E4xdIime6KM+8gQ6fxaqAhagEKwX4rnZzAtu6mrv7jRCw2IBonhO8Y9pi3nrmSQY13aaRPwxObGiSgRteWYvLYDaO1gjXVpihkR9N0n87q0RkkSYQv8rbPgx/lw/azEJ+sob2KR4ameQl8ZmhVE8pTCpLZ6qE6d6fO44bbcFcI2zd9q43q/3xME/CCJzU2N70e8GoKtFH67UGa0OEXkBi0WZLf5zVVtmp8jq3/QcCveTrI8JysubYbsWU/r2rB3yejAe8+5Ws2mxD3SkrbOisqRuQ/zGEhfrZdFa+9cUmZb+AudfG8aQRLajLAVQO/dZ3T01U8BlEMolUl5kHt+LYQlCQy5MlxsuYdJ6LxLgnHk1bjjGWzztdOdocLLPQwR5nbL2Btn0AWu90pJGRYUotn+bXrolYSBZyOEZw5vm/ECDdjgSXKWls0+9JhzSCXX4dZQV4EcqN7Fr87zsm9Hv5hrWqc4MHh++TdIx8RPgcxN70QI2Loss2rLqU7t8z24D/aZdcwBKC6reGOmiHWXkoA+6uUuVMoY38fqwohmluv8qyUrEJwGdDSVImQCKm2ZvU6RAtjj7qAPi3PlCBYGMDuBtoFNRfseX7I4gv1Fcif4iAvqw01W6+CwvwXO8YqF3GVB5QoDAp6IMAtqwjY1RbImelWQeE+U9jg023A1rUhPveUsakZNtnSdwTLQwUJTuxOva41IlXIsj17QQGQbuKDSWSkE6QGN6kMjZUbkZjpojmvykgdJxXxMTPpiqpEMHjJzvTbOdE7DKA2Tqv1ccjfUBDdeXzUbAqBeT/0eOvenBTwRFrZRerkdysECfjROUsCikGKzLKjBEP+GahQ9RLMxjRGfmoMjm/4/1xKBgb1HIY++IBxi/aMn9BMSQ/XvZc6NdH3VDNHgFG+3QorJr3dCdgaslbI3OcqzD+EnfQMuyUOp5mTalB9QFQ85dEM6KaeONrJH9ngQxBQ64rD+b+CfN6KpMauN95/GX1hJtyhMgeElZastZJiEFTnCkvJKIKkM3uFhylWowyuAUa0raBxj5jU+WkKEyBzpLLmIIf2u4kSey46rxESpL5RRhs6l3375l9NS1Ke+6sJFzaOj/ggnOEUfSTSn7nZE4kmDWLJsEKkJ2Jl8CGnR/x7h49r1DvNqkFzS78KmdrNEM+6W7s8v5zKWJ52D989euYpMQ1BrE98yDxJw+/HQtkoog1kTw3ujAgINLA/ist9sWkDZRKBCIzID3JfR0iNnus+268aSkhyYCMJjrBRf8DboprqM3EaLShEUqlz6AWButa2LixVjVuS07cJvxlW1cEGzuhz1B0WE7QwM3XOSpsEUSG4RvyfwF1AQPKSaD/lDBeCSCXXN2U0IYq35FZIscc88gNGArXmW0fGjPu1CKrXRbOEZfmNrv3shCskDU2K4tYCK3H4Zd64T9jPX6JM9QNObQ/8itMGzCDmqsF3SHZPzqhN8FXwSygGhTBYuSmmAX6HuOugb9YxZYMw24rUVqJObCOX0Ctdv/BTcQ9QFx5AGedweq2ElpQ75gzz2vsLY2I9GcKZdna2jeHx+wSWkUyblnenalQm83DBOnKMOXrBBM=,iv:woggnuIgeZE27YluCSaa6q6wVBbgLhr6K7zZ2hxYYRQ=,tag:Jzmixkw5md8mVJPW+5tlPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRUdlU1lZdEpNVE12UFhN
            YU1SdFpOMEtVSlBQM3ZON0FtZFNkdEsydzEwClNLSWtQOHViT1N3OWVWU1hSWHNE
            bEJDSGZ6S0Z2TnljYmRzVC9iaGJ0QVEKLS0tIFBISmpBZGRlNUUvOFI1bE5iaWNL
            eFQ5b3BFWm10T3FveXl4aUpJZldacUkKsNH6F2WlZ2YLgESErwcrw2rAUi+mdkGr
            jrQQ6wxx6BkuwpM8uzmzlJPRrhqFdwkjkCTTr7PX8UAF4y0682m7qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-10T02:16:04Z"
    mac: ENC[AES256_GCM,data:FnM8GmXQdfFR/nCPDjGGNufDOi0znaGJ9qkhrSw6dMewbfsJ/3EEe0kS0MaQ9os9AZDiDiHqLUTrmgo+mxj/l/m+SaANvTQVCTFIC57x5rs0ol2OgxI5WjFzM8lfgnDrue8I9qLa0Cmg85kv0WAugEhLqIa27OVT+FuM9Y2ybno=,iv:Z+muvq/Wiqxr6gKnGuQw6jrB8pdUihHnhdEVxWpKLS8=,tag:VnKY7fGKJdZLAcbvzZ8dcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:6PWmZgW94Vq5WgnGf/U73904hnsuWqpml28KdxCErFucaXkIu0aMFyJN6200aB7xi6tsMeOwF41lPXBCp4vYuRYfH7W+mA/2Rf3HKoEmPuWwqxTaffKSHhtqTpHUexoBQOwiRxjFIwStzjMvlQKp4kpT4c97GXiMfytC0TH9pdu43CREnML1H1QuSUDTl+6YJPPYrQRtStUNa8L6t2wMJ8erIOX8bvqQqkwtP4anOn4Z3vFwDc+OruxoPcAH2GesuvEbQ1++sMdKIXPMAdSaoRUH/3KDx+D7S312Y0ji5Q7dsrJT2UtoYohs5syulljUBNmCo3NOBATmUOd4/U+RJpU1GYcmTY1pVR5z20dpZqTYX9d2LvZZ1iovs/LSIsOZzg31n2JiXFhsZH7vmXd6jZxWsWLixdOefLjwk+sAIT2nz7rxuwJcgTiepfZDnF/e/W4YpujY6M3ANOUiota420rffs455hsf2Dj07H+ZNyFg4/nESwJUrHSuZBiG57XUjrI9FndqjJL9qc7kDh0TdUR0q3Mw9Cv2gM6kjlP/DbNED8Jx2T/JWb7x3G9unpirRSu2LVJ9bHQy9FD8ExC0vHA2CxxVrcI/+nNJnYZ62min/UgiPaUS5u/Jv42ryUuiGWkvG6kjgroPwvq+W0+gcERk+bs+Jt783XFm9TxDR+NT+FbvoendAfBZstPTQr1DUGGlMFzU7uD3ktClE1D5VBGvA7FL/h3Ji/J1r6legkJjbanRrhLGoPzGdK8TQkhqWP1ArH9LI/SGbd6E+/DzpHiIkp0i60z0wZId+N1tmzKNkmtTApS2teI8aJ+FZVPBPujzXdP+B8KP15RqQg0VPVdkMYdWsOWlPzaOOz20dQI52KjdwSuFPU2Q888Lprhx+vlXYZUFD4OOA+mSpue2JuHQkUN/SzCHvhM=,iv:Gt0h4tYEVnfFYnaaxaxcJCullkIK9HgZwq6tKJESlKw=,tag:x7tZllpMmLIZ250ON/H86g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRUdlU1lZdEpNVE12UFhN
            YU1SdFpOMEtVSlBQM3ZON0FtZFNkdEsydzEwClNLSWtQOHViT1N3OWVWU1hSWHNE
            bEJDSGZ6S0Z2TnljYmRzVC9iaGJ0QVEKLS0tIFBISmpBZGRlNUUvOFI1bE5iaWNL
            eFQ5b3BFWm10T3FveXl4aUpJZldacUkKsNH6F2WlZ2YLgESErwcrw2rAUi+mdkGr
            jrQQ6wxx6BkuwpM8uzmzlJPRrhqFdwkjkCTTr7PX8UAF4y0682m7qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-10T02:16:04Z"
    mac: ENC[AES256_GCM,data:FnM8GmXQdfFR/nCPDjGGNufDOi0znaGJ9qkhrSw6dMewbfsJ/3EEe0kS0MaQ9os9AZDiDiHqLUTrmgo+mxj/l/m+SaANvTQVCTFIC57x5rs0ol2OgxI5WjFzM8lfgnDrue8I9qLa0Cmg85kv0WAugEhLqIa27OVT+FuM9Y2ybno=,iv:Z+muvq/Wiqxr6gKnGuQw6jrB8pdUihHnhdEVxWpKLS8=,tag:VnKY7fGKJdZLAcbvzZ8dcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
