# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:q70AF+UWESEEloJ/aEwzBlT9B3wllfvToej/4ErtFTXl0g1P7BEhfUPcP2AWlhYKZHKkKQ2Vus48kwpy6FN3jQolWLq7h11VG8HLwtjUhn8Lhq22TMzaemX28qBDZLFqnPjJSC7T8ARR7S6yoVp889dxphFHg5mLPCB2WYdl2JB44lfUh9cy/tv2+NYfmA5xNJL4HtCgci/hwCErMLjvJXpXmHmxuQG5FXtuxujY5GDUODZuf+n+yi6+ZfWlCkU/3qHBE17LwrGknsO/PP590D9x25SXaIXLkN4Fc9uDrHT/4i9KppiH1kKihKWOHqbx9nZWiGkx4ndhPa9Ew+dLsEvFNl78pdFlwYelfIS4GaK9U5ZgU2LLgCVMxEVxNNK0U7SQJMplIvr0i0ZV9BlEZDgFZjhp/YwkOefhninAdkEfhKAsUUUTD0ZIH8I3mDMRy1/CaOTvD9C0iPLRVpxNFxF5vb0p75DIO+uWvFa/0lFGSZ7moHhGvxTaum1L0yofereJMn156kBO1YgkYaZu4YkGIFGZ1n0M2R8udTpQNXkE6oNUY1btbarCY/WMwyChO1IhGMClIsMX31khF00NCAfVqCYE2cQo22I33suY8Bs4J4wjWpPlZPqpmfOx4hJdBSwEItS4YYHu0fYVnQgDqNstwMJAJLcFjveH0x9IbLoMa0EO2LVCTBH+gA6DMJ4n3TuSK28fiQrHEe2p8iEjPjAHZjFZlXnv5Tl1DWD0d6YXBbXX/rpW55DaAnxxCqbMklOCdWbuapwTuDdKuExRRPF0KMPIXL2ujxhANNMMLNPBXPhga5lbiEXCH6NVueAVkOcAmz1x8tcL9/vcEtwxZbAs+7/yC5hwLDtHVjzFhXqm+UnICBDFzIdPC6+05WbIECj173qGtZc73S8RbhF6mjkojCAn7J7NZoA43YIgldlwOXc6qknDsRWOkMnanIYX/mNvQEmNyKFWhCY+J1x82qILnFgM3CZV5DiEJ4cZ8RGLJxDaTix88/u8U3n5dq0HorSpzU8lKGxwrxeXz5I1YWXx7TEosyid/8ttwguFSedolJVyLg5foQsVMruOncw5KwYwjZhHtT0sWzBZ6XPu0+wxYtSX0w1tCM/62Zj/68pvj49fJGRzhSpfvUlOaqx8lUsHrBUlczIhx+zMmtldGXcKlI+PvniaP4+2395if1ARf65mg4RS+EPsgcSI9SmH4DSDQ9DvvQ6jBOyEjArBlrRceF28KvLBSyEenUqNcCK9HjmIl1GCWFARNKvUjo5wDjXsezDG0iVubSZBhte/o9o76jsvxHTtLWQpD4QJI8wL5U8wI0eOsomOO3PrB0Aglny8XawYIwNr3QfatQWWRUSfApyhCVZ9PeJdKDioi2r9a9tCztC5ZievhBt3z2L3opKJ/JwolMlTBnVhHuTAvfn7jaWP8gMB+YbOO3ukR2EZITPhg/AGIoGD6eCbJV2jUBS2m9CirhyHLbXABxUCvCJi7oIldMPAu2hKd4rxsRnDVm4CcSFv0f7avDVaDCHy2GAkOES+0be2p2HLoNQv2Ubf9Q62j+0oayRRV+//veXD15WuPvMWhcLSeskrUlH4fVTPN2qBVYKe5t7VY9pfVmwd8Fk6StGCV/1ZM/KhWLctrmjBefxU2MhCmV09oJm7AeyNjIZjl8ZCH+snfc5FqpWSyPBUAYovwf/IrchpGVg3Wo5YrBkiGI9kCrAdkS77E5lss4Cg9VrP3gEWRvbpK3Mu9DKUmxqNIV/hGv3WRvW/L1uTbsZBUIni4eltFu3zW8vl9LsAyv/0Ibk8bhs0OoU74HvLP8rsfy2A0VwWTWwrPEvAm1FJPSX93lt6fvAWHfPoPSOZnYjctmYznX6iNyAA/8wzEBu2ZxuOzR4efnRELlZa0Xpkq2utCHCfZFfyNCygahfTPSQE31w=,iv:FefbQWY9LUYguXW992HfxUWFrm8p9D0tSlDBmLlkTn4=,tag:B2o+R1wZxjSk1A9YYhu4xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtanQ3R0xhY1p2UTl0Qmgz
            YVV5NUV5T3RiOFJDczY0OHMrckdWVGJTTzI0CkNUV2JHVW9xWWFyTUFXd0lYWENT
            ZXNWVnFsa1F5YlZaL2RTbmVjc2NWemMKLS0tIGZJU2gzWlZQbVFtaG9MSFBTdUly
            aVdJRlh0MWsxdnYrSGdrYktMRktlUncKYN+C0/wTddlLgK/J0fSDh/6ww1sF4lX3
            5vKVCjvSw9ewsHXILO1aX0TQFvU0AMkXJmTu1C4+BJbtHqAVgS4F9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-27T07:50:50Z"
    mac: ENC[AES256_GCM,data:vSXwQppKoUX9vI6JyGYv2PwNmlpvOCmSa0J1uCLWmQ438M5UVL1RDTbr7Daue6y4ZTBq1vzXcZsi1q+0owzOHlwSQWSWfhHBTt6cugwb2bnMEwucWVy4gR5do0STtBb98uggoIN7d0nz53ib9chzqI7UyuM0hJswdbsVAuPT3xA=,iv:+OEuYELevGlHwujOqFsFg+Igeg6+FXiirPzNnMP8Z4Q=,tag:acdNnv6PQ0xh7Q4latqGTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:Epj3KV/OtvBFkesfi239gNFIMQO3vBJB8JS6b0KzZgPKVm8hXwrH6ZAQWuP6E9vAzFyJJyfAzCBN49JgyqxECm7cr7C7FTmWAvhqFw74zCDa+ea9UzqQxBZEKh28eBSQHHCLbg3uRNcoLd6av9oVdHz3c+09ISOLDHsDs5/LyW4nWIZDMvIcz0jl5zZbtj5lT3elXkrfMAHJs8deVFDK9nyvcpcDUYOcGXsfMjuWlPtLDXlRdGdqwWzTRs0hvORb9Ofqxlh9kP0/EWZqIgcRenYQzemz8FFnPmnoDNS8qLekUguiJuW5fGLcEJvIv8erDDxZYYT7t2dNg3H0VQba0sVZfPPvWZFwHDcYkxi67LgdVjMqRV+Eudx2U9v9ntHULvkFlzTp4o7p9doVVjsuLguWeS9UmHsAXzXeSEvpVBaTzYTGhdx1M6YEBy/NT2pFUTWflNwy/kYWzv4Jy/Cjte4GyG1svT6cNLr9cRalQ6bdIuCXUB23Qck7tvXznbsOjhPzN4/XowksxPbWEmyZMRlvhWbmNu1qJmNUoCSXljgUfBCPo1WCYCSLHhIklEh2YEK6My7ontZcx+PjxKiZKbU9fTOo9kc+LQQeicULBEbBB31pXCS1q74HcOe7Nw0KKnyfyID2ClzzsWAMjswdmfkYyVW4sugPa+YHhaYcVkrf6qtql9pnQeGHMSf29i+GxU3VC8tXbk2JVGYPwcOijRlujQUPJDVdCMm0dbWQ5yEdXYT/9Y3BxSD5XOPgQ5F7Qywmcu4zeOFDPn4d/sL8kFBncAmsBp72H5p2MSIajCPIiuL3XEJwXDU0LIcaJn5puJUVdeSar/Bi6LWk2+QguJWn57HzznSungNEvU+7eu6NAOW2u7oerrpXQKanvJ2LAvjLkcsPd0SwLku3HDLyTvvL2WNWAtWCxfc=,iv:R+tTQacjWyM1J7dvercL0ra8QT33FAeuvXtrOuWpjZ0=,tag:zpGltu3GCXlujP/72Pl75Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtanQ3R0xhY1p2UTl0Qmgz
            YVV5NUV5T3RiOFJDczY0OHMrckdWVGJTTzI0CkNUV2JHVW9xWWFyTUFXd0lYWENT
            ZXNWVnFsa1F5YlZaL2RTbmVjc2NWemMKLS0tIGZJU2gzWlZQbVFtaG9MSFBTdUly
            aVdJRlh0MWsxdnYrSGdrYktMRktlUncKYN+C0/wTddlLgK/J0fSDh/6ww1sF4lX3
            5vKVCjvSw9ewsHXILO1aX0TQFvU0AMkXJmTu1C4+BJbtHqAVgS4F9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-27T07:50:50Z"
    mac: ENC[AES256_GCM,data:vSXwQppKoUX9vI6JyGYv2PwNmlpvOCmSa0J1uCLWmQ438M5UVL1RDTbr7Daue6y4ZTBq1vzXcZsi1q+0owzOHlwSQWSWfhHBTt6cugwb2bnMEwucWVy4gR5do0STtBb98uggoIN7d0nz53ib9chzqI7UyuM0hJswdbsVAuPT3xA=,iv:+OEuYELevGlHwujOqFsFg+Igeg6+FXiirPzNnMP8Z4Q=,tag:acdNnv6PQ0xh7Q4latqGTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
