# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:kJZL07wDuinLDrZCAmY+ts+bHZqWFARdvAbuceXpVkye1TXZ2kLYdPtlBRmvruk+819VN5kCHLS8W8VBB4yK7wgpUuIaw5UH2oCFwhKZXR5oNh0fS1Ex4mkNEvZwESyDmf5kyztMwkAIpfKv3yQYvmsduKeAhjJO5knfVd+sQlLvCBCMrvCvQzULMV9heHxqTBLh0bbO5rlfwl6FNO0jmW4NsSPoSf4lfVIcuGH2TLQ3EOcw4/cxXG63aFNJ3+DmEfXhG1W0V4LiMl1KnzjuyBdIvqiZY3v5LMGc8aq9SICVU4SzbwiSJqSHTOFzEy2Q6RetOKPlADxTNn6i3HsXHORdAkJGdLYAogABIHJEdH5bXERmrM76boa4Jv5+aCIxYyGSbWUF56tUGP6LCdO3120/Pzjv/F/DwoWVVE4w9JOLL3mg4rSy/5GfsKWRGbWKr3xB1VAy+brYEMm0HU0WPYH3fU+Zw4y0wPuyIHXQpbU43zqQ+5X3iOew9qOqEhvsPPHUCOw4YKqMjRZiDZqO1pS7qLFBkKGjGn6V/AhRMlJP/0bosoccirhKDeQFMBRtGQOti9QCZt21Wm+OpPTLKIwXHf+wu77cBbjclvX/50ZOCWV/39LHNDer2LgMISZsjeEzHls52ch/hJXFEjt8c5+H9IhHM5+8DVesffw6UdbXb59zTZSvq0ECu+YtQu8FX5CDVJoRWiMmHS+ZqyvZ6tRMrxRgyqUrf5/Y196hOze3/7Kfky9RcGCXL/+iAwbc5crTgmwjqGYYxZLIMwfVHn6hlqK+cKiGyAbCayr3W4CFLvmVDQdS/TL4kyrJOympPSjAGq2SQ2h3vq1JSVgejgBd/9zdozpOlwDJ0AzG/33f9OTCsFKlM8eFc/4NIe9ol6lC4+Tuw3B36thgkKI7JRFsOb8IYdME6IgSCoT4vCV4ccfWFu7ue8+DxSDhT2wc2eN8xJIOFtNFAqqbVzxvpsrGy1Ow/PhxQyD1+NLbt2PFogdISSjKa3wkLOsVzxTEtzy2ECLRufML7vWHjKLwKeMbhEEt54sv0oKxqGbxloOYVp840vvDpCwG3JijvEJ7i0JqrHW5o3uiOImfwbYuqXL4pzjITiPuVwOMcKqlD9c5sHaOY6p7OibZrUFJb9ydsZa7QLtSigMzKZ/T4uyMKUtvFeiNGuUj15+sf473KmcBqIuLQq079IkWDu9glbRmgkelaIz1jsY8pdceeVV5aKSIJ+iAC0xQMPDaVbUTgNSGNMWPEvPNQq9qKvG4UmUyvtOCLOhE2eq8vME0yOmp43+83OFOzEx3l9pxKzrzY25kZXVxPfKXyXTNqwo6VjjCeJjB/cN8PgbA8gwQO8x3i7Q29WYhfwYhLQ2yZf6EVDBjpgWM111db0yEdy7lAe6Nx9vqxTBqKU8zvmGBoulc2QiWkUhdRXxGkWu0jIHpWFXIBWFW18VXK8amCugb3PwHUs+K9LA6ileOTg51zh2elSht8VfeGUUP+MENFCHnT+q1NbBe/vJMEbegotjgmkebp4vcQ06J3D7zGOxvqzQrX9Sf4BpkJS9ut9eEfEBWoOm/J8uOy6mB6fBXe8i+lmueCfegwIn0M1sL8WUpTeZEIsixOeFB17EpxmmnzEtzLMBlBdV11JNEocx7sfyDg3dc9IuK4NiY8iSyVqoEbjjVhDmx3zoakUCEp+jwTHH9pIgaTW6FPF+VzKSnLAz9GtRm4JVXvgZwD+zFa/aPqr5TTWViKo2S0jIjZhw+bPBQkw+fH/Gb26KwFbzfMgovobXtBtM9VFO3DzDAYv1yN2bxyAhqZkIh7xZpofIzT75yqiHSxGb9jykKXeE3QBNx9PoOeE2FOtqlIL6GsaHCGruiODGyYEh1dmVmhlGOPqxiL/ldIy9TO7ikG0jXML3d2glXnL52Fhi3Ji2KDOM=,iv:1mHnuqEpfUc8jloDR7bCCy66l9m1l88cEM4RjrNn7bo=,tag:rzNqSlddIllF1Z7zlt7idw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMWtQZEgzR0lsdVEzUEdt
            b2hVMXZjYnZweUE2WitZUXNoZGJmemF6ZFNVCmN3bGpBZ0U1TW1lWWp4STNkYUxI
            djZEd0l1WXo0WHVoNEpxN1M3a2VBakEKLS0tIEtkNGdVTm5TYndsWm5zekNnTk1n
            OG1wWS9wbGMvMlIyc056SURWdlpBQVUKdGBIO3XfB7yNUT+BBPZ8j3zcUdlY0r0d
            6b2I4AIhw9qWHfGl7yHQvY2Jo4LuDa8lphIiXRXLaIgX/T7xLzx5ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-30T01:27:17Z"
    mac: ENC[AES256_GCM,data:izsChJIFvG2skwn0c/+4IwGrw33I7j3sC+uKIxGpGxqjfg01ecUwPdBBxN+ykvbVYd/scE4Gb9tRLyaoduc0mExeFcErKahu0eITFJ+yJpp6E0c4vrbO6++CLfIOvgrpvN3uBK5FHplvmEqraWNABJwFlWWc2kj7jYVNpWzg0ns=,iv:3oCFVxJP6wK8Aom4D9Oul4IvhLR7BUNNCyJ898jFEDY=,tag:+VGnXKbjlLGIA/V2A5M9cQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:hsHqp3MXEiRWs/pRQGbHJmXlBDQac9CtLj0m1fXY20/SmojNNWI6q6NnAyiM3sFef1Y//inhQOIFnddF8qhFQhhMNmyhIJDgtUSLapgYiJblj+wKzDn3yf2rLozgVGzYM5ggY2FObjTfvUa3JvsycLM9qeQTgRJWRx8fqOmE7yHldf+eJERiR1O1RgP5Ueo+N2rjsNxhL4oZp8lXq88rJLBUGEzRe+MzaFL+/2fU5q/KtOIXKr5xrVDZIq0KgIiFli/1GCCkUS7rLLRAsFcsTk16okfPiacuClMNCSoJ6i1BdTGk35lMmD7OGOzXcKPbC4L56VLoYP0y7XkkFjhm4dLPeLJIh7jXqmLvr/84jbo2xq/f4nsdb/uauaaMmnK8BNTNa6hSPMlu76PUFFrnercVrYtE2Elo4S7qbW4MxpM58TncHHuetFXPSvEy2bcyZpmXa2PiVPxIcc0c1jtlj0nFK8TIWze5eYMPvyGveCk2NL5ZTCc8uV4zAoRNe/VKIGBXVm67bcbZhWYFFVOFwS2bxwIYo5FFe10C2qpyftFXrVsh3J4LV4rLXHUIIHi5bg4Wa5lE1RlaAZY1hs7H9MtEYlPPiFVyW6ZVPgtW5laIWjPOph2Of3bNfaQsL8xsaEapRaB6RRAQglk/ycDiHqm98k+UgiK7eYqIWZ7rKamUGVcObyqJZ5oGiByc0TS8EwRtv7X2QX9x0WiwM2e+TLUSGlIq8K8ZJn5p3pe9yk6nxtd/APsoCYWjeR1tJBtvGpZaD672pwG9OJyl/iMzKSncgWGrJPemcn2YwISyOz9S8kLlMyC8imRBIrxdqTm1X11qCK6gfYojEa77Fguf3vHDXW8QwtmYmeRiHTOhvoYITMuACiw3olc/9kd8ccN0BT/Tkm0dATbPBwDiMliVrTF5l6PI+v2Kb20=,iv:B2jnlz50blQ2caa/+lLappcqJaltv6AbHhc5DwIgby0=,tag:L9RRkGN9j4N5o5ZxLxOu7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMWtQZEgzR0lsdVEzUEdt
            b2hVMXZjYnZweUE2WitZUXNoZGJmemF6ZFNVCmN3bGpBZ0U1TW1lWWp4STNkYUxI
            djZEd0l1WXo0WHVoNEpxN1M3a2VBakEKLS0tIEtkNGdVTm5TYndsWm5zekNnTk1n
            OG1wWS9wbGMvMlIyc056SURWdlpBQVUKdGBIO3XfB7yNUT+BBPZ8j3zcUdlY0r0d
            6b2I4AIhw9qWHfGl7yHQvY2Jo4LuDa8lphIiXRXLaIgX/T7xLzx5ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-30T01:27:17Z"
    mac: ENC[AES256_GCM,data:izsChJIFvG2skwn0c/+4IwGrw33I7j3sC+uKIxGpGxqjfg01ecUwPdBBxN+ykvbVYd/scE4Gb9tRLyaoduc0mExeFcErKahu0eITFJ+yJpp6E0c4vrbO6++CLfIOvgrpvN3uBK5FHplvmEqraWNABJwFlWWc2kj7jYVNpWzg0ns=,iv:3oCFVxJP6wK8Aom4D9Oul4IvhLR7BUNNCyJ898jFEDY=,tag:+VGnXKbjlLGIA/V2A5M9cQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
