---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/unpoller/unpoller
              tag: v2.9.5
            envFrom:
              - secretRef:
                  name: unifi-poller
            env:
              TZ: ${TZ}
              UP_UNIFI_DEFAULT_URL: https://192.168.22.1
              UP_UNIFI_DEFAULT_VERIFY_SSL: false
              UP_UNIFI_DEFAULT_SAVE_SITES: true
              UP_UNIFI_DEFAULT_SAVE_DPI: false
              UP_INFLUXDB_DISABLE: true
              UP_PROMETHEUS_DISABLE: false
            resources:
              requests:
                cpu: 15m
                memory: 79M
              limits:
                memory: 102M
    service:
      main:
        ports:
          http:
            port: 9130
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 2m
            scrapeTimeout: 30s
