apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:7HE4o900xuq79sE=,iv:e9pTDAyu/wK8KawGwXlnbYRvcMJT1TWG2Z5GnjwrBLE=,tag:i/HJx7XZGUVmMlejgxa++Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fxNyqp2xwxH70Wu6Zpqojg==,iv:I9LpY0yMLLFRjqhucFGjmqIZCOG0QMKhe1J3ehEXme8=,tag:UDkfJKq+tUOw55O1o+EnYg==,type:str]
    SECRET_DOMAIN_LOCAL: ENC[AES256_GCM,data:NjN67E25OgcvuHhF,iv:/OJ+zIAoyr0BOUyPTKr4xHmL/v0gJSlcA/8MkAqhHCo=,tag:9RBHSZu7WxsN+94cf7RLTQ==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:9i91qz4LK5NWbw==,iv:+mky71qOmpAZCbkewGNhUloKRtCgtVB08UmpotVPPoQ=,tag:Skb3sUFNdVe871UhjopHnA==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:M6//oI825Qcr5A==,iv:TD75Tt0DwdbN5JoJ3AFdfFVnNLj9CKq452tzOUL1KZI=,tag:TtQ4j9bVNRJLdkxsMZzwJA==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:Qyblg4eZUANsZA==,iv:qaYoP3QJKu3rqkM6oHbgw79qhco4iPDfSZg6Nhxsfww=,tag:iUBGEblrUk4QE8UNUKNQsg==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:USMw8UNQ9tMhiynk3K+vIpBXNN+WaqsjoFhJ,iv:rNG+RRibleuMlo89XmL3vJi6yhCaYaVvgLeYtRg4cmI=,tag:xfG3u/HyzOi2OUUomOeTog==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:HLf36njp81g/kjUD4PCd2A==,iv:P9zMZOPRWhev5IxaWdIlQcYdRadyVQF/C6M87NykHqo=,tag:H/grJcG2PeXBv1M8osWA8Q==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:+T2VKOSm/8v/YfY=,iv:O7OtZzX9Rw+SwRY5eRFNqCEnDX4KgbX8MtLEdGYRJf4=,tag:2iI1/0ahj61j2VLMJcQ3wg==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:M2YrSFIU1gciiPnidjQLzfI=,iv:IueG4llv6zYCwdWvA7emnoRaTtdGQUzMSw4h17qMiJY=,tag:L91rp4ctbpmzA6pjqlpAKA==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:QrwxRnDnlYNVQFDS9fU=,iv:uHCiesS/VotlUY0JlDx1rOoCZQnNpBO5T+2ia4tNgm4=,tag:u29rnix5kTCwd8xQBy7qmw==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:/CdZjER0wBewPCibMLA=,iv:flMWicmuSdrhlXno0vBzyPXvuVeD5S5gD+ifhgPuSo8=,tag:DbJJPxKDlToAu/G0wRDgkg==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:GTrcu2UQ6d2cSwTjozM=,iv:ztVg2tXNj8+mqauunnOQHMnzcLTFXeIf7lt/9WiwMV0=,tag:r+OwiW65n2gSudoKsx6pJg==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:Z7+EzvUtcInyJODC3t6I25IOIQ==,iv:Gp4v3Go4/hGzou4qTf6VkCbnnI2tSGFg8P6ZoduHTPs=,tag:Wz2nCMxV7ribJd6vWTwrMg==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:Z4JLF3eD+j4wIS4Yr0zDMXHTgw==,iv:yYPgyuKuxbyLV3oapr+p4oQUSchuyqJSTVIjUtiGrbo=,tag:vPSccnot3QH1YWPLKMKR6Q==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:ygNIpAJByWFgTVLi2Xu8iiZsVVYa5E8=,iv:VQy86P9rRwkl7jjDd6UC+Us8ZNw2hJObG8tziYGih3Q=,tag:8B5cLTPOtYXl6/KiNrwAng==,type:str]
    EMAIL: ENC[AES256_GCM,data:MuXWbhtnCQTYigPUrIGYSA==,iv:fKlWXG3FOnS21YaB+45h1jeTMU1N4/0WDX0cmdoTD0Q=,tag:ScK6w5VYgwYHQU0EaKBAEw==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:bCwvsGBowfvbmKZYvb19vD5xql9Cfo2xQoN8CNpzj7cCQao=,iv:stF77sHGK0Z770xkoYBXsQQKK3LrqGVMrR5Gxma598M=,tag:kA8xydBduRmjlTmmeodbBw==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:5ZMwZJbyl0X9OPzy,iv:u5bCNV3w4C7FhliIAdTV8UptZe++LLdofk5VO0eccTg=,tag:yB9qwczQxEbXTAtE/vDgNw==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:1hI9JTnIMe4OWG0Z,iv:OTHP9b0zKASGV7GXIw0tsuXBOmZ8fDDSPeirQeEO+6U=,tag:dNAhe6XU6T84OVsCYOvsOA==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:7Rhcg2c=,iv:gRbOUDDyFPGa4ipaWQSYOju9hOtnSI4suo7SIjZiTtY=,tag:RqRMCKlHjWqfu1ovcr3bWg==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:YJSK6eRtbkYsIQ==,iv:w8B4GI845/+CgS5OBkWkZrVubyCHP4NYjqGzicnpBeA=,tag:8r+rx3qIxpP1RwHQ3LeRvw==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:wWNRCR+zpFMmHqD8T4c=,iv:PmC22i69S+fDy1IhyYkCfM3TA201JSN6GCtFW8d6t+U=,tag:KvtBZ3OfofQ21JdTpezwTA==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:7kVhvZ5CsGc=,iv:Ae67p8mAFgOpJld4YBi8duk/l/YKTuKepiiXmIh4jro=,tag:rd/zIRUU2z7DE4ceCQ/8tQ==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:zW7+6LU=,iv:Z+EaXi+waiqgDGbzBjNnz+jr2iM4fxbGGy4kZ4eNBIE=,tag:u4nGZKbgwKySs6gV01f2GA==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:DJU2ynjmf+4=,iv:g7/qAwVgn/mAxVRuBQ7Z46vMTAJgMrlmrRlm8KLCNbs=,tag:Nwz8lSVR9zpmSQhs9aYjvw==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:+oxZo1uUqb270livZmw=,iv:+me5b7bYBJqlpvtuG/e00a9Ye4IW857iIww4dteoHuA=,tag:80Yfo13t5cJluUaDRYe9Gg==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:DrpmffUWpHg=,iv:fo/+zh/uX12gbanbwmAIG/Jg7NvSqWEqXCXWQT5BfWU=,tag:bbkzW5CWb9KjOXERU8Pkrg==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:T0s2R+QOoo0=,iv:TGI6rKNmJFKD2z+o0+xcwnYqRw6p1h0fE1NUjVQwG9w=,tag:4gbm71TlEyh+Ld4y91TPHg==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:EtGIe1GZpt4=,iv:kBi+p8ZEri2Ark4PVGZhjl7Sq92zZnit3cj/zPCUInU=,tag:vN6v+ctKUJKcQxE+poIxYQ==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:AIOTYb4UTF3p8x7SChLUexKskJxwbg0hvwc=,iv:cb7ULbqz9Sapbp26U2HNoQoWalGKn1Ni9jCkKRtn1VU=,tag:gFZ8kf8DkJzgYH5nZTL+aA==,type:str]
    TZ: ENC[AES256_GCM,data:+f95MOipfLwquH9irBqsw9pSQqc=,iv:kclqPvBk9TlUXrskM1rfRvmTscVhdINLQpOIz8KOl38=,tag:zAuVGLkyhGwtdaEr7au4CQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:WgfhFcTDCdgOwdyhdM/TRYLQO5Vi87lGg5h9v7l2IvgED+ucICMqKmamFvdAeZ87aSETz08=,iv:uQxQRyFI4Chn7PwulRdU+CpFpqbj0YSo9ju8fLo6qJs=,tag:feFxf9jAulY5yTFQ1evbbg==,type:str]
    HARDWARE_DOMAIN: ENC[AES256_GCM,data:xdiecnKlbwBGMA==,iv:EcUvy2v8tmVe/BrKGR+jLM1ZIWr/wiji3sKIiPPiKcQ=,tag:fS3xHPXEzg6O7TVIBoHQDg==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:PUlFKEVlPg==,iv:6WEifMOFKwT7P1PNV7s0nT4XT24q8SBaITlL39F3c1s=,tag:Eu6MGhokggMKVspYIYFDnw==,type:str]
    VNC_USER: ENC[AES256_GCM,data:oLFjRxQ=,iv:+DdcovTWFoGzmfqAYi6HgoexiPNu8N32IS0CuIGaKVQ=,tag:sSXStnxaeSXcvUH2Z6dnaQ==,type:str]
    VNC_PASSWORD: ENC[AES256_GCM,data:CDFXd9MTNc8=,iv:ZtcAsOmqgTo57PJ4CwRdhxpJe84tnyCvNeH/Zh5BRKA=,tag:HX93+g7ChSQVl09Gdg71lQ==,type:str]
    SECRET_BOOKSTACK_DATABASE_PASSWORD: ENC[AES256_GCM,data:fUf8QTuLPtI=,iv:ZX0WrB+c7m16tWr2Jlugxto14iXGHqZpfUuTCVCrC58=,tag:D188Eqt9tBeHtKU7bK9WJQ==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:AoVOGikcX2A=,iv:3rFOmX0DLphtnuZlFzWjEiQxag230BznIoNbdp1bYtE=,tag:JT5Y5KuhQ6i6/rgdd4Y9TQ==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:uzyyON4=,iv:wQYFTwxGD65ml9ItubcTrsNFMW8J3zXSu1zYSogXbvs=,tag:BVayD8HnfHbE6+fc07wYvg==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:2fWaclGt0aA=,iv:jKp685wjRBoJs5uKMnOa/IWJZZu0/cWKuswhN3W5gXo=,tag:Ro70u+5L/JBucSR2lJIbRg==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:cF5XwUwKvncydA==,iv:p9SdJUWSN1rWbjcafA1Uagvlmo5SSW6i/udvRJOiRhI=,tag:zeQ3IQAwMq/9iTDTN3Hdng==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:k1gdS/+r+9ayRTBXN5By8Q==,iv:UG6nlCRUGylW2wOXaPNZGkPeWJo8A0eb4/m0ROC6S2g=,tag:ZY4ZY3O2lpeCvRwfYALfsA==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:nKbXHj+tExY=,iv:Kz80JTkDvO1+K19eRYLYiYW73CQyBFWlRkiSszTM7Jk=,tag:vuj/1UlRWvcJZBaNWbZ6Ag==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:RJ4ibGZQ36BinCIfr3S0+Q==,iv:YS/l9ut1o6EFYrzM02lb25XKAnAP23VAiasOKHWXraY=,tag:z9LBcJtesGEB3QHbXQr+lQ==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:Mb1NDIFZ4qt+V18=,iv:1yeHWbQczvdgmfYS0TTyjM9DZsqXammtRYTKdAU6ZXY=,tag:+lSloaPbEeP63toxQGmWgA==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:B8TbD74DvBHq8xEoq9V3fqzZoBfU2THpBr4=,iv:nFmbGZ0FNNoR+tmzTGDuPKdX2BCccG06gRKe2W1/eiU=,tag:jUksgyRsp+hDFQgs1TJDsg==,type:str]
    OUTLINE_POSTGRES_PASS: ENC[AES256_GCM,data:I28QSMKIFqSFIKh88uj37rwaz+2fax/ksCQ=,iv:L2yTGl2ny/ZOMVcxoptbsOOtpWarFGAHtutEJ1oZ8P8=,tag:ZDnXeJwBXAMGLtK31ZWgeg==,type:str]
    OUTLINE_POSTGRES_USER: ENC[AES256_GCM,data:IBAPu3q4zg==,iv:rrHsMFuvM41TTy3HrLrQfbyJuXMLs/U3p0MHvLQsZzg=,tag:TOLeVjjB9AOBLcB861Fmzw==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:1++fHvB+H14XEWgNJ1qhKd+OUL1CyapVthQ=,iv:kYblYkgdUyITzmlYMUKmW6v+DGr5HjrKKBodQz5ND88=,tag:LIJMNPrbLQtE9wQlYuN/1A==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:CHb0OUf0GRodDp2T21l9VBgTh7nJiaNSMGA2DulY5Lo=,iv:aCbOuUPElvcqgmZ5yRu0J8jwYxDgoiXakq2+CfUJVM0=,tag:y+YaJUbED3DLqszryIo6VQ==,type:str]
    SYNO_ADMIN: ENC[AES256_GCM,data:7d2nxCJnlTw=,iv:BO5VZkppRsnbKzecteLMW6QQebaexjNJgPxeHWVyxLU=,tag:5ABN2otFNMvROtNV2KRW2A==,type:str]
    SYNO_PASSWORD: ENC[AES256_GCM,data:tJllI9AtzMw=,iv:1/hplun3Pi+FfMHJBsKXfpIo7KJU4FOK+Sllt5y5Pz0=,tag:X/+Z33k+UOW8FILzV/0wHg==,type:str]
    NAS_SERVER: ENC[AES256_GCM,data:1I0yJ+fhKTjKScU=,iv:ko0blZV/mRkW7q0JEeyT9P8duGS7aAQLa8Ib2Svermo=,tag:sBRByp+AjIC1r1Efu01/LQ==,type:str]
    QNAP: ENC[AES256_GCM,data:owtC0tBXiZI3cKo=,iv:slwdfZrxlhAyRkT1j675+AN+n0113G1BobE4l5wyGUQ=,tag:zaXqha/F+fEkWItpWoJ/rA==,type:str]
    CUSTOM_WEB_PORT: ENC[AES256_GCM,data:Du5uCw==,iv:3dnhE47epP/P3W7UqKdi2Y5Ex4ZuYrG0ZPqE3YmULJE=,tag:7O+z0ZR1wjZkUuGloe0kKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveWkwSGZjOHR2RUhhSEFL
            WWRITTF5QjdCbWNnY1o1b21nTE0wUFpGM3drClAycHZUYUxWZThUbnI3NmhtTFVT
            ek1lUjdqQm9YVlhDK1ZEb00zQTJCdFEKLS0tIHNlOWIwTUM5eVE3bU0rZ244VkFa
            clVaN3BoeWJIc0Q5MVNWSUpMbGdLcVkKOzqLf7iHLt3isQe2MCg6bxiYpwDAoux1
            sLId4mGxu6tlv21bs0JYokx0u4UIVc4yqZUlGYGfQl+r0WgVTG3Vkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-09T16:00:59Z"
    mac: ENC[AES256_GCM,data:u4WJThrVehm8gJm6WMFNzvkEh/tdE/G82DIRQS3UuBAwi0t3NjyT57VbslssjhAkI1M9hFClqZ4PqPf42iZTmFZwDcbBVWqesyKvmqoaViGjQCjez7yf4NrQx8qvVsErNZpSV4Sh1pUMsXKU2Lk4BdrQ/FfP5Rr6zxARZoN78Es=,iv:fZYzWy83PKGumNsKr661P7308swc1PxbhsHpIHG9hBM=,tag:5htxoq+JziAfrS09bul+aA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
