apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:VfGfu4B2IiRfZReU44dI2A==,iv:71jKyyPvoFuBX61TV4tQGOG1MocC18ZFLgsSdnrqKEs=,tag:SUorZTGN254FTmXd9li3Vw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:AJqKTIXdXDNTQyu3moIm+Nmf/u7yJzoihnZ9LpCutEWBEG+7,iv:ylZ2Q6zhVpf7OOq8rooW3WstpcEMFguBCOosJpZmsE8=,tag:fGUtbiQAyqw5uX1x/UF81Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:C9ag9+ly1gywvYY=,iv:WKfwaJYS4q5vOrSym4g5RHLnFsbbsZF8AK6EHC3ouMU=,tag:2DXkDkU/ObamrHAAQ/w+DA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWFd3MGYrNktJZW5qTDVx
            TGtPUmdwRTBaRDRMQmpXaW5qd3BuWXQxWFU0CkIwcHZyVWd0MW81OFg2TFJ4QmdM
            Ry9sTTJWVHRyZ2pURDRUdFp6MTBndTQKLS0tIFYxWUpnQ2RvVDJkYUIzbGNzTkdM
            UG1WSHBMR0FMSk45V1hPcWU2ZzBUU00KWqKnnaxx1Ewy95BFdQGlrW9cknyzYrA0
            u39ZYOGYclb6SICs358BGm+htBAfRvtKjpPr7F53AHk3fMEQB4O7Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-13T05:36:52Z"
    mac: ENC[AES256_GCM,data:U9Hlh+ieX0g/LrF1tuo/oSFZT1CWA1+WJlLTdxifdkhoBhpiWlBtB3G8OSVEbLou8VK9Mn2bjgqjfmxs1aV/uxzMtqW9ZeiNUbICDMIdQNZoTl6l/6e3IUsb+e+dAwqJIYMtY2yPhUiS/J8fwisGBVjF1NUQhWC6F0d+vG4kge0=,iv:Tncx1qS2ElV8vjPnVyO5ou87Gy6nZdp9KkirmLG1khY=,tag:Mel4PkBKZklPZ3nYcnQvqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
