apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:MmuKgpBQNbbSYKwF,iv:i0yCrwHqah7Np1fcpkUOboSBscanVRj2g3/p4Pxn29U=,tag:r0+RWKZZcRy0sUb09tuY4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRlVuRnZYMTBBYzUwcWFQ
            NGI1aWRmMTdBemg2U21SckR4cFY0SERyTENjCnAveUhPRXdjcEJjMGlxZEg1U1lx
            MGRhRTRqNndJYVVJSmhUN2FpME1vb2MKLS0tIHQxZkptZm9NeE92T2doVE15Wkxo
            WE5FaGNtNVBYMkV2aVh2KzJBWWFIc28K5nHICYCKrBKz5zYV0kMuirYEKIR+IHP3
            Z66hrhVkJSwteFD8Lf44AoO1bs41VCcRAu1VVic7nQKIr7EXtPXCIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T22:08:52Z"
    mac: ENC[AES256_GCM,data:75YeIfKRvaz8idZlieO2U+lHxUayHWqg9s/gs4mOuQCILYq5YXTF/6xkmavPqhjZ48+sKNfL0JwT40HnKvgXhScdBCbjJ9DGefC9YtXuxjrk2UWgDTeptbYmoPZlsHMGQzSwtnatPlpXT/gCNdC0BDf+H+D5N2qOvIFVHkr+//0=,iv:vLzouz3Yqey4W72NwkKb7NkNp2immtos0YnqF0KLn7Y=,tag:FqkAhnQVAvAlxOZOlbWiRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
