apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:FbZCXmq0m1gC4tY+6roZXA==,iv:OWulLtAupxdF233J1gfhz7qE3bSIKp4bucwnSMM8e84=,tag:WE8hTLmWQf3urN2cD+DjdQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:pQLDCYS2aX5cKO2YiRvCdbxq1Zy31A7/44aYZidQ7yWOb3bX,iv:br0uwNcPoGdPGza7A8wnwgrOORTrdwxVslmy/O/hPQQ=,tag:YbUHvvSg0CTz0ZNJfEKgOA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Jgr+2AUxTxYwNC0=,iv:gr2raTjxHLrJHvkAu9AxxvqtNGrfnC1pfUObIU9q0ks=,tag:Pc/sGwfKrM/JB5jQQLCwhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSmpWYUhvNGN0cTArVVFU
            Z0YxeFg0UFZXdzRVck1SRjE3TnUybkR5R21zCjBPQ1ZxWkljaE5xajNDcll2Q291
            dm02WjlXemR4cWZTU1NVcEpxSTRGUUkKLS0tIDJEYnd1M0V3eTh6Y2NMS2lRRWdu
            R2NDdVlvU05JbXJzWlI4WGN2VWo4NHMK/pcoSdpn4QRsORFnMzxn2O+DpujYM5ZV
            SZJddPrqvzy+lt3uI4KMrZNzjEfbAzc+2V2yZWpYe9ByJCgQvVuUHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T00:23:37Z"
    mac: ENC[AES256_GCM,data:Z5/iNHgACANC0xqfsJozA327l4lgwcIhwuYoy7awonyBQJrQXbcwTizOljN6/uy514yh+x0wAoKh4UpwVaoKyBE9Ri/lEUgJGL+1se1N5fhEAY9mr/70SaVXI6fzguz1as7MuVjn6TTPlmp3ASTCHkONdf/v6ciYpEcyJStyyzo=,iv:5/HZXnnLZ4NYdZNPzwykYp8/9/xzhswFBxOkl67S9iE=,tag:4SSaLeEd0YvtnULp6h5Y7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
