apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:N8w27hR7gA6jfb0XDGkfTQ==,iv:B/mPqhdoiWb8kkUir0WRVhDAPPHmwoPLI1mkxaM7Xdw=,tag:MF11a495T2hIMo6WOFcnHw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:IJ6MhsatvJZLLDWyfiDnibqER9SDKeX5sEKGIOw8bX4BukJz,iv:/+8RKcoyw6Vc65LVh4RHIm99jF4YjOt2VkTZBlCt5Hk=,tag:0DSX5sIKx+zn5+GGShWnPA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:O/YgExN112zRcZg=,iv:CQ8k4gTg3tMNXnllCC3uxB+WnqIZcR0pPtjeoPUWw88=,tag:viKhJft1ItcJcoje7G1QHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcCtYQnY0eUpVWENyMWZ2
            dk9wTG5lRkhxdnpxUWhoUUZ2N3lHV0p4MWpJCkYwMGNoQmpkY1BDZCswVUswMW9Y
            RUU4M0pTTkUzc1hJUytlTkVJaTZCOTAKLS0tIGppdExYTVdEZEg1YXlsRXRlbW9z
            QVFVTnhhZDRCN3JRcWNwSzZtNVgxSXcKm9DmyAw6ML9LxkLivSmKO3b/tFkZ8zH6
            Xp4th77IVFIwMyvNW32QJTSjWSTKrg8g/cCgNCCkvjANCZkhxIRcUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T20:09:57Z"
    mac: ENC[AES256_GCM,data:vYsIDM8hMyP6S8P17ZdDHod67wJkVM31Y1WvXWGND2Fz6utO7a/AYR2HMg3+w3mErW+MXdULJ9PhplTGqiS7VzJZywfB4l9BwLbHVbiwMH05nX21GAZNRugE9S3bd4XrlKw+VD+tUGR2TsTv850zECRw84zfQ0KQug5QzTRF4Iw=,iv:7jB4n/JucDA+X9AffDNfbObZHH81jNARxu5MNB1C594=,tag:+2fiaB+mkrn69rUsWCG1QQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
