apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:b+1HtexXOCYpSVk=,iv:Y51LYUjOTKL8k4gKY3EifxxWmJnmLG3A8LSqdqZlxfY=,tag:Kkx8fcOM4taQJk9j5nqmAg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:H7Z15BSoptKsufh9OgppBg==,iv:xeO8FeUKoxtP1DJ9h+/SnuefEC7P0sVizFqpCompMfA=,tag:Hu3hGy5ic1wSAU5hSjHSrg==,type:str]
    SECRET_DOMAIN_LOCAL: ENC[AES256_GCM,data:h5D5IwPZoaNu5Vjc,iv:kKKOIgcLRdzFYlMFVcBWLluqyuARo4/5G1+oa58TuYY=,tag:rXT/OgzwF+QciKIZfP2cCQ==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:CP6o7+LaBPHWMA==,iv:dJqokVLNPw2anLLXCqV5m8Noi/Q64x4RI5t0Dd/Wwgc=,tag:Uy0QzQcHOilj7D67rbElxQ==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:CsI9pgZlnN1QmA==,iv:dY0Y4sW5KQv8y1WqAi8xjIQ0cEaxEYkDUpp2wBytoxE=,tag:fSqKR65xBOLoTaRyw2U/6A==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:dn05OiJUX0ub9g==,iv:Kuy2v2Oa1+s3K6EVhV2l+c6BhuGwdlmhazhYYGBPW/0=,tag:+2f7hrRTpQHjrAKNJv9A8A==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:vkjnkOuzZZBMlVuJQn9/Cy0GqFlh634tEj5K,iv:8MDa90ctLh8xVgSc7N4uGyGYX6wKBBd6BLnB8mIVORg=,tag:+D6DSHOR3egY3Jjk++F10A==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:aXKquKecWOKHa9o/ctTpgw==,iv:8BycCLLt3wg1843aHWKCkHlxSbC+hixOA/2IIFHzTvo=,tag:tQPw0mL3msQzG3IX5zhW8g==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:YjCAAS4bsXpFGm8=,iv:Z1Yq0sRuXSy1sQyqeGxPIyNelbJttcq9rGeU3qaL7Uc=,tag:TDHEx5cq4KP5HuSJF32J4Q==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:3KMQ4HaMQk1OuRwGhsIrGlE=,iv:YMCVyd5Qk9Vcu9Uiwadg92M3hm006APDlLhLwWvnCDY=,tag:D+Qn49+3TB3/baws0ZjzUQ==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:h2+Cw40ERJeRwwwI5X0=,iv:yl2GQyHtOlFCpYLiuWYBGO1ISQN8ghppasOmtHmh0I4=,tag:EgPap0xwDUKNbG6RP/kusA==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:nNG0cvPFb5ApKnWnNxM=,iv:LE545UfH9acLmb9HxRxoduqmKa0rsTTk+ng2z6lzImI=,tag:AnUJTQdbHDrVfMVFN51MzQ==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:UpqtFnDCiTKXJ3ZRj1w=,iv:jYYQrkL1jtsG1LTvr6m82ZBI27IN5x0I1RmoZ5tz8UM=,tag:GH/0GdRi5EnhEJ4A83CxYg==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:TvLENwxlLEh3Yc0A+3qCFWvNnw==,iv:9f+ckWPzBMMODKTAAgIlAFjQBMYFW3K5ZB+9qMMm+tc=,tag:1MHVptJYE0eeiLe3YMIIGw==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:x8OWnixHahmq4CCEUMkGeRjDcg==,iv:piUGaKxxrhl8U6jxGO93soVNkIanJq0rKJKMuljDOX4=,tag:WHyFozoxNSsSmxBcJ6wjQw==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:D0yM/cax46GFn7ioUouisS1fP/nwlK0=,iv:bBfNAJjUC49o7G3MX/SGllrKICFJ/U9h+1En3A2NEbs=,tag:BVOuC8Zaii91aIaJmmrX+g==,type:str]
    EMAIL: ENC[AES256_GCM,data:usmk2QCsMwxUojj2k2hqGw==,iv:0inATNry7TOvkhufIxkyNrH47z0eFkIaAYVyayjpkrE=,tag:kV3vjxaSla7r/di2OgWDIg==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:DH9tJItrNsBFZE+9aMSkBm5EYzKEVGcnxMsWqaePJzggTFw=,iv:QAxJmX1fV3p61N2l8x7W0IpVPYeb70ZWs3xZX+O8vsA=,tag:3LhcKh47SfVvYwdEPo5zsA==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:sYY1ULB/r1SNlNJB,iv:zTSdeKg1Yyq10npj6bKqp9et5yiu+hVlRn/WRQFsWao=,tag:GsDldmZg/2P7mFdfb0jLVw==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:vOpIWqTs53SntMiw,iv:CvBvt8fKtkgEd9ESNes2gu3PRg21UKiuprsHe67Chbg=,tag:+xgSN3iMn49UjSVlQS+ghg==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:o0BQ8Mk=,iv:I4K9VfM42sqVEuti/rx69NVz39zRAk5EuEvJ65i8PGQ=,tag:qHoS7rOn6h2SondiTKb5Qg==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:6e6wc3xBeTM1ZQ==,iv:7VqOnRyfMBmkyeF9rcniGCeCw8n8HEyNqUkIUmR8zk8=,tag:iYgwqcmhySwlfX+bGFjTnQ==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:f6fY7sB0JfAZIlV3jSo=,iv:5R0dUR0NZwyZjercx4FCe2eI7NZ46tDTTUKgvFm//ec=,tag:JYxkYudSdb1wF/u6yi/3dA==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:Izbx45culZ0=,iv:QuyC3kQMHgugu2c/HQI0xGymXQuRUCiI82U+Zo7+UbU=,tag:F5EPkIh3ibUdTxT4Gk1jhQ==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:GCm88Oo=,iv:++TRvX0dJ9T4I1BmuevEG9/DwsyjIMkzyaTFma9IiTs=,tag:lVHLsEFArop8gjnIfqTjDQ==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:Ssi5/jD5CVU=,iv:6+RQvmp8waD0I4be4HYVjW9v+4wfyawY8VrqsXAZKSo=,tag:FYxjMtdVDjiLvuO5YvbdKw==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:AEpQ9gTJXJYiGZXVZfQ=,iv:Y+KLwkCwFJvD2KGlTpRrUfJYM25KqnPtF9jNtAQsWWo=,tag:dOKOEYwnQwHoCn3Cyh21Gw==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:CTHHjwQOZ4g=,iv:AtUq4gk4cO7ThE0Rg0H/KGIJM2WjOFwpH+82pqt5tQA=,tag:7zcbuqfrTyl7f8lvYstI4g==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:s578B1kW9Tk=,iv:ZV80SKhCyypNrDe3yAjFDBcqVS1dHA0kRml/slupsYE=,tag:sV7iJlkLvjVzcSRdCe5clw==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:YkLTV2p5g6A=,iv:07sKo29jpWD5TDaBfBksE8Xdd71Qfg9ReImwA7MgPzM=,tag:cPTux9pEL+Mn0Rb3lugwuw==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:jsmXjnacfgk1+HiymycnUDTvBIaSi4xfuw8=,iv:CPXci+EPxU6UxJZNqJTewuCt1umlV6lgFozSO1xkC0Y=,tag:Su+CbHxagtf9UGrID5fkrQ==,type:str]
    TZ: ENC[AES256_GCM,data:GHEdmFong7D6krrl5D42V7F1HHs=,iv:yPl2bTyFaUVedCJ/chgFSNQ5KKN7cDYet6AwoGeHwPM=,tag:w5NJzw0FJiuDpEdHrGUKKw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:hp+HLicXYthu8A0jxfzsRoGgnjr8wc0SV4r/EaG3KquI0Bj8MX3gwdHGngHldLdq60Sh8S0=,iv:vYOyaZVhk8Yh+MUIWwns13etoo5uXX0vXAzNX7zw11Q=,tag:mJt7mg8G8tgMzUfn1chPPw==,type:str]
    HARDWARE_DOMAIN: ENC[AES256_GCM,data:5M3AGeZBofgICw==,iv:hRv1slLKDoof/GH79izA2nyYjT0m8kfmVSHU9EojO2I=,tag:N1xm/I+Zplgjx40dJOb7DA==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:76gEIySU3A==,iv:bIp+2pZNsgfbQC8y/hD5SohypQa5HFAMe+58Ct1M2ck=,tag:S+G5M6wmYad5VLkN/1fOYQ==,type:str]
    VNC_USER: ENC[AES256_GCM,data:E6KaA30=,iv:DnjmY1XHAE199P7a7uZFzfG4eQpoPccsq/c5kHdzjSg=,tag:W3KwXaWJVJWxspHgJ2XByg==,type:str]
    VNC_PASSWORD: ENC[AES256_GCM,data:VCVez+s1gF8=,iv:qO/qbaAk/GHIBmG/RROXIkMsrEMB8zDxDBBeVZqpdeY=,tag:NRL5GFCQjGjDwfWdtYYyHg==,type:str]
    SECRET_BOOKSTACK_DATABASE_PASSWORD: ENC[AES256_GCM,data:6KqqqwzO8XA=,iv:8rEF3jN+WrYHW0y5NSvfHv5f7If3zZF67YkxmnqDXj8=,tag:BBTVsuqY7o9dIw6eWNropg==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:xE3086uWhM8=,iv:a/wnUly63HiDmPwEklSrFU+hIggfmEK+nvk31ExFriQ=,tag:Sk22OjIJ+wR8pPhya5odxg==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:QfMPjIY=,iv:F+tPVw+X2JUr1G7yQAKWK5q3Rqhc+oWVISUIhRvFufQ=,tag:WPEdH1aWx6tF+O3xlukqog==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:Rpo9thlENBk=,iv:DcYOOUcXy9SzbxcodvKNsu1q/FhZMHjnGxB/aK3bMFo=,tag:X3BrXaivpcsIpMkFMHmMTg==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:WS5hBTMqApMaig==,iv:33trde7oRxPsIlw8IBpoIcrjDCxf/EivRJASV2W0VXE=,tag:JgI+on/zlKRxOfO2Hdl/BA==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:vXxZ4ff6bprXyP1XSFGMIg==,iv:n5OxMgVMX5drsRq8LHpS6wVJZ/UrgWo+RN4kAYwn3VA=,tag:GR/1OrnnHK5dSqr1ZWu7oQ==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:w8HRvGavvho=,iv:h+MtRNts5BgtMW9/CBgMrS1CDoG6RfA1cSZ17B7IOAE=,tag:yAnKudHSPa5pDhlKTZLdAg==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:UWxwfK6TXRk2Oi/qUMknPg==,iv:putNeXq8jcag1hVNELTiyQrr80vVwydRmpWXcZS1RNo=,tag:fHamM/7uAAelJoswV2arWA==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:u9vtwemRq7sv5bE=,iv:s1g9DCLAD4o+JdFTDKOpr2Cb17uG8KMTBAm9wgUbXcE=,tag:8GewdX3tM+1GdVr/mif+7w==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:bUz5ZfFEM/4WkW3K3iIa9p64cpzhXJkwQ5o=,iv:8FNSk5fGAE9Xvehtzm5FbeFy/2dFB3a/DsCOAswCawQ=,tag:8rh9gPxo1/OmC4mlOLJkkQ==,type:str]
    OUTLINE_POSTGRES_PASS: ENC[AES256_GCM,data:5FkGkL72s/ZSI0StIJqerjzpCPXc6xcT7MM=,iv:aLloSe5Xdx/s/Ez/+Ae6lNkc3Sk7ntgx9sX5PPuYinw=,tag:m4PQxdWsPS7aTUYuSliM+g==,type:str]
    OUTLINE_POSTGRES_USER: ENC[AES256_GCM,data:urYbp6WB1Q==,iv:zt/M4uMvao3sztpS04F4FsDBg0KgzfM50tlMNcA5KR0=,tag:fNTwsLejSuM3mxJ2KVXLVQ==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Zm8C6gz80ecZtQvLFhsO2F+kUNpoKPCMh9o=,iv:70J4jofy0axE7igLJX4KQHrfcxuMdb+WdW+93UbceEc=,tag:RD0bgdxdEvrUb50r/l1F6A==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:fwhziCtnxQQCnjexOO+QUtsYOCP82lEyNH0BKvJAeSE=,iv:1uC2kB4bBM1dwh+XLPBm4dX3pfjHnQ/HX+uOxYSkQNs=,tag:Nwt8GavJBkVWmu4Ji6Cy7w==,type:str]
    SYNO_ADMIN: ENC[AES256_GCM,data:gV8m5z0D5oM=,iv:D8YCq9SpELCYQ2GDQiTSjjWQaxDx5R16ROC/88SZNQ0=,tag:BoZ+0wmQwhIWee+hXzW+qQ==,type:str]
    SYNO_PASSWORD: ENC[AES256_GCM,data:thW2xrPuyqo=,iv:OiYfeLIAIB3HW/Pn0wfQGGzlj9Lej/4PhRtPcWfNHx8=,tag:Rjss51nurEkZn/4zdIk3Og==,type:str]
    NAS_SERVER: ENC[AES256_GCM,data:ai0c1uNC3YnLSMc=,iv:/1L0DoSedSlnEjwwReWdYK1VGgdOQa1X9r+CZ2rPWqY=,tag:3QKNwwFVu5OfIgzS6SQMvA==,type:str]
    QNAP: ENC[AES256_GCM,data:qVDE4bCnjrzMDsg=,iv:z1GKri2ea5ZMYtECbINLzWzrO3MFl9pDW/+xnJx549k=,tag:UpylahE6mg5PA04iHRIEaA==,type:str]
    CUSTOM_WEB_PORT: ENC[AES256_GCM,data:jVmwKA==,iv:P8nypjJftcjRbfjRjF7JZ9wOSR03Hs1hkzpPr5yAUOA=,tag:jcHDPVUb4DtpJ6BBd2h/Sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRnBOL3pRMkhkbnlwaU95
            UXNjU3AveVdISXQvYXdXbU1IQ1ovOVlxY3hjCkZNcFkwNkRKQTIwS3dGYUVycDhz
            QjRMODdCWUxPYUtkaGtmZDY3QVZKUkEKLS0tIENQbGxicEVyWk0rU0swZXcxWFNR
            empsNC9xMitObHN5RVR3elR2d2FRUk0KM5lvaZnfmQazusGeBlTb5PD6zQHxdi9O
            rgI4fHdwyiS+dDzmhOsHhdmXzkI0TCoX4sfIrOgM0BFm3vyXB7QBzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T05:14:10Z"
    mac: ENC[AES256_GCM,data:hs0nUTR/ygyZVfT128sCK2hXD1jbDknYAfeaFLc+Gc6VuqS4Ue1CdaP6HGrIR08KDJ5fgyXAa9XEtJ1BOIUoCDsDYdMWWbDfjxAdf4OPEiQKvY6vYLh5ziHn7wLaE5+E895p+eUYvkPrIikSOrwlmvp55qQQhIOlVa6D9zvmwg8=,iv:3zk6QxKgNYPhjkobLv7eo8Li+csAhXlviL/0BNby9ec=,tag:/oHCt2/1td+hqiDd2i9B7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
