apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:0qHcdwcM8F0nFrdyhXIboA==,iv:gyJ4dVvklE0VlWXLfCi/J+3UEYliTMShP1Dl9OhtoxQ=,tag:0J73iZzDhWnqChTuHV/ibw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:hGAaOobVPYN4kJT6R3k5WGs+s7FFad9IYYQ2ekZhleHRkX7l,iv:dtBDFwBCgegxa96rfAOCckP1AvzyxaxEE+vwYLlNbhE=,tag:N6wE8LWDWuLlW39R2rp26w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:hs2zv/Y6+FSLG7k=,iv:gSHKr/r3VKNZH5v+YuYOH3ZdBMIQGR3XRLWo54EsA6I=,tag:95BpDNmb7b3+AdxFAEQ+fA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTHArRzYyQU9Jc3dsak5h
            K3dVbllKNVQ2MUdsd2xjTHNDK3hzR29mUFFJCmdEc2JOcnArOWtUa1l6T2NLWXlj
            L1VRQVhVUTJvM2toVjdOcmhVNjF4M1kKLS0tICszbmFQTnRIb0RONjVIRVp6UDN5
            aVdGY2poSExrcWdscEVCdWVBZUpFSjgKr7bW5UX2sOHaoZXjgjeCfrXTq8BJmqIm
            PjOG8lWSrdxtFR+2A8mU0Nzw3gBDwqNzS4AEOfz09avbZ3r6S6zs9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-18T07:17:19Z"
    mac: ENC[AES256_GCM,data:V32EEDXcKSJSppmnmE5z4NAy3mvDCReQnywIEJPQpzR9+FrY3hGb1+U2AhSHfMJ32Ly9owQ8NRQRS5dGPPDf9ABnGE67Fv6hLXaLLQo8sRSWkJlUL3g4aNNVCMHsWc7PC+23m/c3ksbSjPlKpfgb2irId3g1ooBZ6xbEnMMuK2I=,iv:YWXewojx1YBwV/bNEseBlBNwHdln8+/hJvPeqrAvLWM=,tag:mSyWYYLdexHBbBbV+jDGPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
