apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:p/YoTBHk+1quSEU=,iv:RMdX5bdjjIDPwB9kQoZM8GBsWjvaEiaO9qXdfTeTYB0=,tag:0PMiKltsk5WxbP1RtY2yxQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:8pR+pq449BcoSHEDGGBg3g==,iv:TDUUKMUvJb6jhn9UO0g9/XifWVIkwR9Nj+9qMi3ds5I=,tag:8xcMXoYK+nYJWiwBWWR8mg==,type:str]
    SECRET_DOMAIN_LOCAL: ENC[AES256_GCM,data:z6jueJLpTd1tv+uN,iv:5Vj34gsnbVJB8ObJNo6MJAhftXq90nvYc/rDwI4w5Bg=,tag:I4UzZMlR+FcZmEqBWxii5A==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:0prTuMKHKHQZ5A==,iv:OrgLfdZW2zDWaCv4qgnB/zGnqz1vSlWmXzPJ6430vx4=,tag:sV4SJMrnsSwhbUU3yEGAiA==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:2Qn1VajcZNW8rw==,iv:W/bDDKP/5KpiwHgvkAmZZ/LrpviMgiObL3lar9aeUD8=,tag:N0p5EB2P/DWMz6zGfb8O7Q==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:1cLPfNQBeiEJTQ==,iv:6e75KPXedXhSfCJklRn3cmy7M727oilhJ5Tzh+kpT8Y=,tag:PC0F9LnvXgFAqrcbaMfPxg==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:kE7ps2E4EYGVZ7mu/Hf40pQE2enBBYZ9WlK3,iv:68Y1rIsvMGgKCg1c5NbPkeNFYDTzXcb3cc9az593H8s=,tag:l4j1r8lfiFsxF6H3Q9Pf0g==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:s8du8Z1q7AFziqGYrXgg9w==,iv:bJfFRmv0lmc4zxlL8fiwKU6O8+EZQn4CzeU+3OngZsY=,tag:bPC70vEjM/H8IFgpmDYGsA==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:w93XEKtcMWHFUA0=,iv:9vGIXtqU2sTyWYHjeNFNN12vNJMcjrnc0UX+lQkY/WI=,tag:/Lfab4cm6ybJ4qVxYJvABQ==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:HfhowW2PD8sKiZ0NkVASvGw=,iv:k/s4ZV0reySnvdEBd1RnWEYqa1yWimnAGNKzaXKusik=,tag:dgM0LG2qXN2aqLUEjt776Q==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:PFlEesGUnUgNTAJPz2Y=,iv:At+99dhhKroGXRiB3oiFA9OCUboamXzHZZDeH0RADok=,tag:cYzVA8yFi3ZP/i5+f4Fx2A==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:TXYgSrwb8Ixm4rJN5Mg=,iv:uuKoemkRxeXreAKpxWbAg1RCGFbnbSJwFW3agb0TECw=,tag:UQnwCty/jf/PW4D1cbzTsw==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:d38cGi+JNOxDlYueffU=,iv:aVp28hLSPs0Ei96bYrWlkDlfB/es7U1cr6NtqPun6rQ=,tag:RwTtDYSeaLdFYkgnxiIXWQ==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:43/FGsuOmtiVFcEA+45wa7iLfA==,iv:fk2/Bb5JPWBT3h9cTAfBv5jrwq51xR8uWGHPF7iKdD8=,tag:gWAOASq0lOK3dopcb66r6g==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:c1yFMpXvTMUKZW5zyKnBT1FsbQ==,iv:eDEm1icwm+GTogqtUjpw0O3fg90bTz69tyoKOQWtoyA=,tag:z+uJGq4TuZBVbqeLmTtnSQ==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:AusgInoqi0rYUO4J7LPwGdWvphP+gzY=,iv:OIDGCNhqGVshry+wZV2cDT96MW18fQ0xRcG7XTKNQp0=,tag:xNvf68ywVyiKXOzR5Nlyaw==,type:str]
    EMAIL: ENC[AES256_GCM,data:rs3efUfkiMz23HH9gjkJuw==,iv:zIhBMZD63BpbiyRGqUQoqWo1y6musxGUGfzX3EydqsE=,tag:ZhHCi+GcX9CIDlyCy/DNOw==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:gLw7ll9hRIkJ1+mmNvK2PuaG5t7Ays8mW3cqfmbDHlxszjc=,iv:gzmKRUmTbejsb3KbfjF/Mi/s6fDQJ32WvjarRSemaGI=,tag:y2fWvyJ4bJg6L6PMaFsLAA==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:GBTSbEoNiudPVsSM,iv:8e/uHiXBffm2A/YS8EHx9q0DhsvjwWOE5GR/LiwPsMI=,tag:/gFiQC+MdIeUqRaLbPjzJg==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:RIG6Q8dcpoyHkHtp,iv:q1dOLOS83svd7uqoHgDDenUSKc57qw1phloJvAHDjaY=,tag:tjutyfAygZ6dESbrVn1hPw==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:ZOlREHg=,iv:PxikXOldcHa69jiIkD7qAK2WtFnrfOrYxKjXNrzexEE=,tag:1ec0m4YkMWJLBhSwyMTQlA==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:Dk957+ojSD0AaA==,iv:qc5Br2eLA9HVTI+jAGAHD+06zWSWO1Ijm8h+OoHyzPc=,tag:vnDp0yUF2eSucI/PZ2Whjw==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:8rxOnghH09PvAMMoB5w=,iv:dJO5AO3FIy4tJnhcflFhSlVxIkpJUWVx3PUgtcflzyM=,tag:AohCk7knjBJxsmb//Z0jmQ==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:S345Nxgyis4=,iv:HslaSiw0uVf5PJ+hBU4ZbuLyY/O2fP8/VkZW8LkYhxQ=,tag:gmiKfL3WEGxWanZKOwXQhQ==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:gE7bMiE=,iv:LAlEc1umd0pSuZhJIdln8cSTGMCbR3r8bBxsgGH/3VI=,tag:+vJs0SUZc6jufjD9U72YvQ==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:n5poiqU9Grc=,iv:/ZsNgw1lBS9dyDg1NIqEZI6n2fjig95wWuEsWjyR4UA=,tag:XudDSDApF+YEjNA2E2AqNA==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:XSsm8Fa8v/KyJfKhdtE=,iv:mAQn8gVBXam4ijVEyYu5+fYBcQ+02jvIdyvFVkOToaw=,tag:8sWfEKdPDn9enFWpbQUVtA==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:ZDkStBksxSU=,iv:YgUHEuL1Ef9tJjxxbZjVOU4PewrxHXXnaCaFQxT2w64=,tag:NREFZfsQ7UjP2/FxK72TJw==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:3hC5VMiH5NQ=,iv:ax2/ZLDjOR0Mwk+/cd8DZ7XJtfKOFu+LDCyxe/LzJDM=,tag:EjpEviInLb8x0ANhfL2uyQ==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:/wWgTJNORl4=,iv:+dj42vKdJ0r3sKxkjynWW92Z/nxov/amXn1qpbg4lxM=,tag:IKIntPZUO4qbLoVRpIGE0g==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:a1v6Fmf/ikEZeE/wU2qWIEjgjLqmjbGYqrk=,iv:2eG8/grgGY5eUsB4PO3LBuiTgER/z+KlSHJzD8nF4Tw=,tag:7cwDq96MShfLTN1c6004nA==,type:str]
    TZ: ENC[AES256_GCM,data:gGBC4Q9YE2vrkszpUkOAFx36D4Q=,iv:M93hyGkl7RYY49py4aRLzsZysd+3owGKJL5mB+MbVt8=,tag:iRy9jgXQ6pwUyVSy3bCCxw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:7ElLASgIH6O/4dAP/TKwxNOJfwg+ZYluIAfheFEBM3A1uj+1mO8SeXGkO0h3IuaCVHQ/qts=,iv:63CPL1Nsb/BCzryZ9LWnyim2SuOdgizDK5Zz2evQPv8=,tag:+sCTHPgrFRWFgHkrhMOqRQ==,type:str]
    HARDWARE_DOMAIN: ENC[AES256_GCM,data:pyIyNGq3s5sT5A==,iv:aqbKrkD41RBrsXw+yn7YPLf4Y1BZtmchLz/7TDAqt7Y=,tag:Hrf8nfWIz+nVoOuE+oGZWA==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:BWBC9+RYCw==,iv:ZawUVDuNquJ10Sv7e+9aU7uNCkeBHBsi9KdERLUvbGI=,tag:2CwcQqFrAor5qy2P4di7jA==,type:str]
    VNC_USER: ENC[AES256_GCM,data:z5fNIag=,iv:5SfXH+AV33NTiU0dL3zjP+LFZLTGJWjyZPzYZTzdJS4=,tag:oC8bPILq5smtBxIOufIC3Q==,type:str]
    VNC_PASSWORD: ENC[AES256_GCM,data:LKX4cTUbsb4=,iv:hvi5K1vNDIptDEssLitqJe/mCMwvUqJw68UgyxvZuQU=,tag:s7wwWti+YcjlVDUjBWFALQ==,type:str]
    SECRET_BOOKSTACK_DATABASE_PASSWORD: ENC[AES256_GCM,data:itsYE8D5fE8=,iv:ulDdgVaI/U+NAhaUfYhH5RJZ4rMTYaR6e4oASn336Oo=,tag:y0prHgRGQKZmcVrQXKcvWg==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:DHrTWYUyw90=,iv:M8A58FXqTLmEef57pKQFqrYT3HuN7OcIkBF2Zo5Rorw=,tag:jBRliZI5hzK+QUUqaKb+lQ==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:WG/Li+g=,iv:vo7uceJ6ul3Gl2CEp7ACfHsmio9tgzBRiuMByMkQ7s0=,tag:3pOzCde5Gw8uuUMtioxiDg==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:ZY9RLeLtJwE=,iv:kNBAP7y0hUJbNA6oUxLdGN8t9+hrAhIXvCN+IzyvC/0=,tag:kfNaTyrHyBoMJXBZp/9EqQ==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:9GfgEqzBAxsGCg==,iv:C4FXug65MF4Ye/SvRZ+x9OqjpxTkFtsoNvdycesay1g=,tag:EM6HGtQYLvDrUBsvpk6ENQ==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:hiVusPGxl22sgtucSXVNpA==,iv:cFhPJ1Uv6SUme0pw2k1lqgKnJ4f1bOjhzVQWh4Bcwug=,tag:wNGTWe0yF7g8/Rl3W+omzw==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:mF3C07foOY0=,iv:P5ExvO+0YgGD81IkyUbma3cJh3cJP947px1rhwEcbt8=,tag:TSROt/vQJ6L8CGRu7ywzTQ==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:ZPZjuHhmJFqbQkOt+u9MLw==,iv:8jf0asPZoiYVZrfTcyJSMkIRNTKvHcErpRVlinib63w=,tag:C07Az+L5tSopYeYrmTcw+A==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:PsCZYXMpNRPRGLo=,iv:suZkQbVHYtzyjm2JhP50c3aEzQjAjS6qbCqVFHSAG9U=,tag:pSNYgoywlFu2hSmi9VfEZg==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:g4qYP5vznLC5cqK3p3+5Ob9bnmMbRDNZq4A=,iv:QO9HydFcoWd60wz1Uw+HpvQom4IhywuBIsYVcTMMd/M=,tag:xKOR4Mf/Y5JDA2sBQhLtmA==,type:str]
    OUTLINE_POSTGRES_PASS: ENC[AES256_GCM,data:W4810CePXkk97m6WLMECB2HKRbM3y1+KETA=,iv:C2mf1Vit7BWfhyzbYusLogRET4DEqbQA7WnaM5B10zs=,tag:aVAxbogV7aMEIgvqSEkuEQ==,type:str]
    OUTLINE_POSTGRES_USER: ENC[AES256_GCM,data:8Sm+ReUgIw==,iv:bEwI6YdL+lX+uH+pRZaVX7bXArULZE5chwbel66cNPQ=,tag:Z4tsgWnaxJr/wbRM+IKihg==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:BUb6dy5wqtU3HqPPjbwyXHRbm8a73QztPpQ=,iv:AqsK0GeRYI0TU4tjS4TkAizFmGcHjH2CTyx0T9qLgPs=,tag:gn59ZpU3EIQTflB9nCvchw==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:0m/LBdCsWIBwVvPuiNWUB3ylr/+2knT8zFrEpHLpl9E=,iv:M1PoMK31qaXmIYA4pEdfCKb8bE7Cz2b1HFvMU911RVk=,tag:00Khywq3Empod6Wt01qxjQ==,type:str]
    SYNO_ADMIN: ENC[AES256_GCM,data:Jom3Lw1RCrc=,iv:WTW+DbLV36gPUOtskroC20/mjfWGOcM4MAj4oq5/w2s=,tag:0FgeI5TctnWZZTfdD4g58A==,type:str]
    SYNO_PASSWORD: ENC[AES256_GCM,data:Nqwz1hDhz4I=,iv:6L3gTkmj0qycKI2LHn75BKJnM41SxH4abWnsehdIaHM=,tag:8qni5V+94dPdjnAUutLZDQ==,type:str]
    NAS_SERVER: ENC[AES256_GCM,data:KHNGnwCeZEXuN88=,iv:et2IxG9NB8qENQxpOv9LTlODhEfwB8aO/fHP04serpY=,tag:vLBrEame23IogMCR4HfGug==,type:str]
    QNAP: ENC[AES256_GCM,data:w6wOC1Y98ijIAOU=,iv:Y0wsH+aJQULpl5IQAWvVtpcbwz4hfhCszcrbTWa7BVw=,tag:YYF7i7OdLkuaXJn2NyK1QQ==,type:str]
    CUSTOM_WEB_PORT: ENC[AES256_GCM,data:LUs99w==,iv:fuLkELyccOxgZ9zcZfeVUtM04xk/eR9+sPAIgMAmHH8=,tag:xha5KRwvg7W7e8nGh6z7rQ==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZDF0ZUw2ZG85UzIxQlZY
            UjhZbjNibVoxZEpYUHdDRmZlSHRCdDFHVGtzCjA3RmlLdXZHbWdXYXlyVEpMTERs
            dGJZOUNIeWVWbTBTYWhLenhyS1FLZlkKLS0tIENYb3VXMzhCUEhFLytUOFExVldR
            RlJwNUE2Vk9PUTlRYkZ1RklZVWtpVUkK+jd/XVzVBsU4icyrL7u4aDMdN/VTKlQI
            MynCjPRz0j1UblQWK8WVBTR6VF+mu1fRTqgQ99Xc0arnttXYAvsHuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-13T05:48:59Z"
    mac: ENC[AES256_GCM,data:rdk3clXlKk+A310oMGOdF4uMmA0LRQTbhAexLJe2oAey4I+D+kR4YuQV4kapecs2A5HfV4dOPIbM0srUwF29/oddv7gUbNeD1L2ORClHJ0YAj2DorAVpHEPJaMk2TWJVg1kITFPDcU4Eiagq0oWhv8Kjm9A7C6pmL2d/PJo9VDU=,iv:IMNZJzgKo52B1ycmer3njm8e+PuzregsGQ7WK1jaavA=,tag:wgkuVKkCYIXJlpezNritNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
