apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:VG3sxoErWaCtI06sWFrndA==,iv:UHh+H92wJVflZ0Fz39/C5mP1QDha1ezbJ3pDHnk1VpA=,tag:PAWKsBpGBuJsyGi3/E9qXw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:hz722RRv89YWkfWHl+chOV0CC07gCI35Z87pklgvJtQ5m8mm,iv:HmqxXKvT/P8Yp3SdWFFcv8G0tGV2keA+P3ymtm159zY=,tag:Y/t6HS6zN/uPRtHEaittYg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:t0Fx0Gtwp4w/nW0=,iv:R4Lv+JIiVxF1ZGNEX1MMBWpoVjDmnzDVWjDvo3KtyVg=,tag:OtbyyvQQimD9i9gy+/OeWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TkhuUUFzZWVSRlg5NnZl
            UzQ0L0hPb2NTODZKemhZVVpML3E4clJlT1NVClQzZGVwVm10ODk1L1Nvakd1d2gy
            aGRxaGhzaVRPK3hENTh4MS83RHV0b3MKLS0tIE9FN0F6eVJoZWYwRzRvQnM2ZnMv
            eWZ0VVpzbjhmcDFVd21zckJ0RHBwYWcKnNFOeXUkod20J3H8qOCm+qNRgfByl2Ah
            1s0pnyGkY9rFtbg30nW8lCpjxP9YJzyTOKmNfiD+c1bSn6nVhbredA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-09T16:02:14Z"
    mac: ENC[AES256_GCM,data:s3H261IBK7NtbFKSEiSuXyVsRiIwXOKt8cb6UONSeAqoom/TTGuVIIBUupLCE2Vh/fnKLrJ4fHz6Bq8eaALTBFEzI05AnvfV+2+orUVnZPxq5FUhRFOGH2+1b3wViKYFqcIWWl/pUeWRm+1kDEhQy5uJE7YuEeKGhzxksnnPO7k=,iv:eZsq/yhB7vSWrecTjkiFVy7bgJEf+xcg4b15IpJOkQw=,tag:UKh/fVYhG86Y1NOO8HvV9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
