apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:rbcYHr8l7ACJlrM=,iv:wYNTQkvI6wWrFp+vHl6zuL8AiKMDtu1JmQTn+1/jqm4=,tag:CEA9bBCP4gKw0DJOQybukg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:HBWpor122XYdq83JxlP37w==,iv:QXhT82CAwGM1uFcK/oxcD5o4i5qf7c+Y5v0NevB2wf4=,tag:KYV639jJTbn4f3kPws1z/A==,type:str]
    SECRET_DOMAIN_LOCAL: ENC[AES256_GCM,data:a4M7cXbSfmZbSycx,iv:RCvUvY8ey/lmr0aYjY5bIEaNQytXXmNIQ7VzSxGnizk=,tag:TNRlKeMpZZ90gp4Kpnrjdg==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:8WyUo4BKk7C4rQ==,iv:PWFFnUIicSGmBlunPNduTKJ6OcJ6rytPkm2l8KWStr4=,tag:+dlz20KSrTXBWauXaI/hEQ==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:tpySQt2kKV5fBQ==,iv:P0PMh2p7hvuRX3ej+zBSxhBZPYM/uT2QTTs//qTSiLI=,tag:IjaE95H20pVLpgZnHfJsxQ==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:lHepsaetlpa65g==,iv:tH7OKb5kU33gqtLGcbjFGzaE5uC2g6u1jGSrQskSwac=,tag:xPofca/ydqmqSPkxHLMrJg==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:nqMXG2dvTIFpIVbLZf8IKf0s7FIY4bGf0EzY,iv:pQ2dSyZ1H5EoG1nOukRfQcnu8HeU9ByaB1p0lalbrP0=,tag:WkKdiCD9bIfeogbveSi+/Q==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:ORb1LhZU1pS8boZ7rSAcdg==,iv:Jx2x13r9xXsdRMlndwrIx4hOS9quVn7ZaCf15A3q2us=,tag:0QUsORHAspRiu9CJV/0/jA==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:Hyy6RCYAzsuOP3E=,iv:krx0jB0DxHRwkASpZ3ltPxbkBWAxC2brgi/hhwom89I=,tag:AkiMA4reIgfSgucjNDTy8g==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:PcBUSUAe4hnFHWlZ2OVKAmQ=,iv:qEPH5eXif3ggzESUCuRTcJT3Fz+5akzA1VOj5LQJm/A=,tag:VCdp/8MfjM4APlZXY58E2A==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:8i+pKN/wEwgfJoTh6sk=,iv:THiyIvTtNfR+for8HsSQUV2LotPMRa2vqbZeHl2X0I0=,tag:p6NpVDTN6zRNQvi2MFVCNw==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:NA3G25MueK2lLeVz71E=,iv:Rc6sNgoJFR0d8pe1CAMEuGTdOYDfK5xPsZyZ2SM8RAs=,tag:q7C4n3D+n2RSm5sS69aaaw==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:5BeyRCKN9MJCIMHvMGk=,iv:JmR0k6NzI8SMGotRIjX4aUbxtRaSi9vu1Mfs4TY693I=,tag:hKkYq8cvmwkfpKAL2izbTA==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:WtFG49dblB7hYTBKP8q0OljCzA==,iv:MsrPM8/MbkY2TW8dq+M8YHSyDsWbDwTBo7Kzam0OS/I=,tag:NWKmi+CUk8hvWwwTQYBOEg==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:YgRQ4zwTRq1aF4Pvg1O9vpPBxw==,iv:c3J8psZc1G+gp7VeTQrrJQl6gH0noY3SSDqI0bQsAws=,tag:5WaJTmfcxk0G3dHCyaNdCg==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:L28nvz9kE5OHLK6vZZsPU344A5Kj9/k=,iv:kC1cf1/tNncVktjx9QnTyV6u8hjldxYh8QrU9358dMY=,tag:qFwm6snJ0mMNtSXTREac+w==,type:str]
    EMAIL: ENC[AES256_GCM,data:sRJ4tGykAxXXSkTgU/MwSw==,iv:U9zITxh8f0Jm0HW40nmuDwHbuyZirq4mhbv+Eb/MdUc=,tag:t3icAq3iA6i2Y8P1ZU5LdQ==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:YAxinqxOPzGcgn1evLlMacx5hcE/PFqH7ceNDFwbIChCwyo=,iv:Hstui64eRn01mzYdaScyziRDzIHKWhslSLUgf9u8V+Q=,tag:uPv27WUI2bSBJW+hiyXcOQ==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:Kz03GHdZkrgoTG3O,iv:69122fvmzR/qpRqX4Rdb+bRKvN4u1qQuyV4BWTgTauk=,tag:dvb95EewzKCjCbwrpRMymQ==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:0gjr084gb12DZb0q,iv:Lh1a6B6ICe5UJCunLygOY7stcdqiQwVhGKNrSLjLrDc=,tag:Iy+2YYRgbDOjAPOOyBn4gg==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:LRUFVH8=,iv:1y/Fp/RQITlDq5Jewz0yZqbXd7Xkx0Hi0pI5hXbUMj4=,tag:3HuNpRidRsKtHD40s3CY5Q==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:pU3B1JeaAJD5Vw==,iv:e98Cw5iNyGG4E/MfUmc65M0k1wAnN06asXtAovpLd/U=,tag:nX5HmA9sfGyAjngtQSb9Jg==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:bHHUKvh7VJvVYqMQPG0=,iv:cUGUityxU4bBA8i6pwlTqn44uJJ4fqQeZBxMDZvXsKY=,tag:YDrjfqhFubLStEFte30okQ==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:+pNLa1PCg10=,iv:V24ZtACmyFmTaNLnkALueFKDiHOQDQipoZ9brlxXY5U=,tag:wJAjSxJUexZA/GfXObMrKw==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:MMein40=,iv:qNLE1FE2DAHj0SsQcjGk1k/sN+//yUxZz46wIvo2rjY=,tag:T5edW0GvA9GEknqd5b6d3A==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:+Ek1OQnyMLs=,iv:tZuP3VpK9Bb921y7bm0Hg+I1h6zeccW4+q0+pYPwKa4=,tag:hTJu6kkJt51XibRkBVPh3Q==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:UzyKojSzfM37FISFIms=,iv:q/szkB9NwTs0yYO44x9K46FYsWFpXbgqOPmVCaWpqu0=,tag:fcc7aNB8V7amnJeijHY9tA==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:t0gi+xDReys=,iv:LvYHovO5R09vjTWnaGYKkipHDocCjDM6j3Vx9+guBnU=,tag:nqNwuWq1NNjR5ggA+bn/gA==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:peDYstfPEo0=,iv:+bKUJbaIzLLWbrStWCBDUyQx21DogrJvh3E+Qmn0xDg=,tag:i7ENdCGZgKtc33XJVzfyUQ==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:Q9e9nxow8LQ=,iv:ncciz5cHzd1PBzLRotE6+JyKTQlReeJN5q8cuyca874=,tag:c4L0KRtN6HlRlPHBEpX4wA==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:1dOdKldFvwjqRLmH06Ped0ib3rNInZ81Ydo=,iv:XDIGhNNZMfVlS6XjW55Y06TQv6GxOrXAWlWUmggpK8g=,tag:A6bsv+viSjub+J2Fxq0yvQ==,type:str]
    TZ: ENC[AES256_GCM,data:F+sdIh9fKscmjUIDBpkTmd8+UDs=,iv:qWN0VEElpQXJ+ALJn7Og75DsjykH0s7oFPjZkZr7TL8=,tag:TJkoYgzS97QStqgzsH1YHw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:Rofgq6jI6JEj2fhP1hoVL/pNpH9hFHYWWhT/qCvUt4QA7rButhrzVVOqkAWGdS7uIBJZr1o=,iv:fxnP5E4gkGDTXZGS2TD1PUh4rqvJ5o+lEAKulT866wE=,tag:eIeVDdeq127LhA4yM1wAfg==,type:str]
    HARDWARE_DOMAIN: ENC[AES256_GCM,data:CkWcD11+AvIMYA==,iv:3LRcS1136QHm2wtMQkFnHGhC3reh9mNumTaV4v7xVNI=,tag:8fDplUibnMB0gDc7W6UxBA==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:lZGyR8Vz+Q==,iv:zDiSFvkZ3OtzvAI4j0P0DNFI+tPHFoJpzpQO8ksNkQc=,tag:JmjibIQIquiWQieMt1s5sg==,type:str]
    VNC_USER: ENC[AES256_GCM,data:LquGFU4=,iv:IvX2klBE+2fYUvYHS/QM69fM4uQSFMZLu8ReU0XMfaY=,tag:Idp25B03fMDyy0jFrdHqTA==,type:str]
    VNC_PASSWORD: ENC[AES256_GCM,data:vc3BMgpg1SU=,iv:Pw7SqNTFftHYMrrJpEAHBwz/hf7fLJwR3WgzpBMr0iM=,tag:/aB8iGPnvg/oTS3mMlMqIQ==,type:str]
    SECRET_BOOKSTACK_DATABASE_PASSWORD: ENC[AES256_GCM,data:lCrBpZ/kv7s=,iv:hlS/7YmwGK/qJw4pUu+wppUwHXgyzD8xzKC1vcvTKHU=,tag:vim2KybGgLaGm1pz+cwngQ==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:Une/jkOQQGo=,iv:PWoViE7AW+ZEwKDvXbzkalLXJGo3/I9kkYEHrGV90KU=,tag:yOS3BSWFhdjju/GVty6n9A==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:Rxpu+z8=,iv:XgfhTay8q5GsExKmDkVdVHHp1KeHIwrskfIydgEaj9A=,tag:nf0eUL1Pre0IOyE5JaMiYw==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:HTBFDC4miEo=,iv:Ur1oHePdzg3pXTRzYwqAE18fb5do2Uxoj4rW7aGhO6Y=,tag:B0lN+fbZexTaG1NwW2KWmQ==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:NDpoFIR15pH6qA==,iv:1hx8rx6nWkd74XXVf9aNeYXky2xXAWcWZWvYcu3HqNg=,tag:D/gGFzgsMdmlr/aWHPxzkw==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:QDKJwosxrHx+fDj0ufllKw==,iv:1adZbwFw1sKYY7B/sKX8JuIXqFZzx9jFNsVYSUVNXWw=,tag:Ejz0nKkxYB3tVfkzP+XYLQ==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:WIoD/4M+2kk=,iv:e/wsVjg7heIApBlfTruiTE1dRxM1AVqG69j3zDd8KcQ=,tag:KZOCAreAxByVr4v6GIOcgg==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:FRDBe2SEnIvcqC+vS8Xs1A==,iv:ONGTHRFxjGiVvfd8988XMu1ibzB2HIeapb+JiTb2HBk=,tag:Iqv1hYW8dQMRAe2jT6Sqxg==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:nqpPET8kMRijyTc=,iv:kmpQfWl9Mbppg5W/VqjEnpOGNCJn4dKANMTwGHCSq+E=,tag:pGsKo1FV0746kUb+NTDhqQ==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:WdIJYT9eU1WmuQqeo7haCOQaTgMDBk+wvkM=,iv:m6XGe02Ri9ltNtDpHP7cZ7mwgBo/p8NDRSV1wOegCDk=,tag:IHji7sSnUzbtaI7gsFqN7A==,type:str]
    OUTLINE_POSTGRES_PASS: ENC[AES256_GCM,data:h7g3TnM5/pZjxy27HhZ5eSXiXvPXcxRj+/8=,iv:z7IqjozNMdCXOpqx8p95zN0PnZ7IHNwf4rLCVjKAJQc=,tag:j9jDiRoDsMaCL7EhXTBbwQ==,type:str]
    OUTLINE_POSTGRES_USER: ENC[AES256_GCM,data:qtux83qyrw==,iv:BgmY7rA579Cr+vyY6LWFa303qUXS+xJlyz59hDGYkVQ=,tag:0YGQlsjyncaB1xPGtGwPsg==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:e+qGrxZLVeqQET509Znz5J285jf+Sbl/LSE=,iv:fuBXwPAwqHYE1Q+2miVMoO3F9l7RLZB6Q4FqqJVswgA=,tag:U+JkWkNsqsRd5hrX7tyibA==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:KA5CnENkIL7ZSplP8W750kSj0OJXysb62XhbY1gx4ik=,iv:lFyV4ae2GquD8q9rv0S5zlxb/5edPfk+cgDNT92s6y4=,tag:i6kHytIF/MoUpf93XZMTvw==,type:str]
    SYNO_ADMIN: ENC[AES256_GCM,data:yfGNf8vyG0Q=,iv:xkrnEDIXHOiETVS3xSxcBmd/SOsJvwC/JIU2shfcLng=,tag:IzKZDnbm7C5sF8ceaJVEtg==,type:str]
    SYNO_PASSWORD: ENC[AES256_GCM,data:+dwh64tZQ0Y=,iv:WnvzmOryC50fMhtqprTfzNf5u7J3MhH042a9JJCoN5I=,tag:WbKWreItE5ZbGZwjq6Kwgw==,type:str]
    NAS_SERVER: ENC[AES256_GCM,data:cc8T7KNEFH3aouU=,iv:ihfOtEsAzkSTDmXkVYpQAqdT5EXwePbhJhTEunCNi0k=,tag:U/qMClWTmvG2DKIZEB6BwQ==,type:str]
    QNAP: ENC[AES256_GCM,data:G/8j0vukgz8DJUQ=,iv:kxxBjcqZsMKsjf39TmRtjSybhORqUdoqMdPa3Myx9mI=,tag:EE2odyC1JJBcXXBwHVmB5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQmxtNEVMZExQcTJqaHZX
            dGt5ZTdlSDNNRjhlK3JTeWk3V3NWSHNyM0JvCk9DRGF2Vm1ucDdLSjBZUVBGaW84
            Skg1Uk1nQSszUmVKWkRUMVZJY29DRVEKLS0tIGlIbUVhUCtzTDFiRHlWb2loRkRE
            LzdHREl0ZGMwbXF5aDVja1RMTEhPblUKDCX2TrsYD/Q0rCfR+pPIi2FqpH+HAVwY
            ennHrLfM4FN3VYKK+UIgORotIx5HTYoA2PqM830+jNazbZlj7LFetQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-12T06:00:35Z"
    mac: ENC[AES256_GCM,data:SQs4fFpSrZ5jC3pE1oODggw5ZyIjCqmeyakQ2fK1lcdddXUD5b6TbaKKy8OMu8yi6ETtWH4IyhyjRiLMDSqfmrUZmQN6Vu2CXVYMquau6AlDW+xTjNtGkxqVK2O0Och1/71CJXoEEFQhkcq0171GcPVJb6yLdaWnanjXuCAAt04=,iv:Am46GmFcKNypYk/bz/tG1WzVph44sle6R9vvcAFtBQo=,tag:Usp8YC2wduRgc0igzem3Bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
