---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app stash
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: stashapp/stash
              tag: v0.24.3@sha256:9ba5be09e52a91d7d4387dfd7367f1d6524981e4cf8fcb95101ac28110aa4310
              pullPolicy: IfNotPresent
            env:
              TZ: "${TZ}"
              STASH_PORT: 9999
              STASH_STASH: /media
              STASH_GENERATED: /generated/
              STASH_METADATA: /metadata/
              STASH_CACHE: /cache/
            probes:
              liveness:
                spec:
                  timeoutSeconds: 3
              readiness:
                spec:
                  timeoutSeconds: 3
              startup:
                spec:
                  timeoutSeconds: 3
    service:
      main:
        ports:
          http:
            port: 9999
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: "Stash"
          hajimari.io/icon: mdi:box
          hajimari.io/group: "media"
          hajimari.io/instance: "bloop-quarky"
        hosts:
          - host: &host stash.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: stash-config-v1
        globalMounts:
          - path: /root/.stash
      media:
        enabled: true
        mountPath: /media
        type: nfs
        server: "${NFS_SERVER}"
        path: "${NFS_MEDIA}/shauna"
      generated:
        enabled: true
        existingClaim: stash-generated-v1
      metadata:
        enabled: true
        existingClaim: stash-metadata-v1
      cache:
        enabled: true
        existingClaim: stash-cache-v1
