apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:2g1Fe49z/twvYWHMNE6p/WBpa1trdICdQ13Xj3EtvfyA304a,iv:FrIPDFWYzZblf00dLJ7KZdp71rgmUAKLBel6FHb2mLU=,tag:z5ODT3drcefOxcoIldpq8A==,type:str]
    credentials.json: ENC[AES256_GCM,data:AMNMiyR1ALBFuVeuixNtiUExBaiP55KivQCT4EjytLH9ZLPmrzSRsaza8oDdorKKQBag/VVoSymQUBVn+wQPzYNfz+lz2v9Ubqk08PgQaxcCXvVCZO/KygL+Ppvfi9PDs5ZT5hsNgKRAiHqQaW+HVJ0BVEN8PFFGObDX70KUUyZvYjfNkHYWVd0XQK671uBkxrFZRN9+BoYGHGs9Nzqw6elpL1KOb7P8KcpO8C+RaA==,iv:lysfa5lv+k+WqQWprzIGsWost2Nu91/u0zxx5BSs28U=,tag:+DzQCxeQ4Un/lrVGzLrTSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZWZVbWtkMm9paGZIS2dW
            MERYWnd4NTBibnhTejJCdmRPRFM5MnNBVWk4Cmx1ZTJFUlFWSWl5WDlheWNiTDda
            S2NYNUUvN3dDeTdLMjg4VFRoaEdwcHMKLS0tIGJTNnJkT1pHV2NUTU4vOGhSR0NP
            aFZWdDlpWnBaZkVVTmRWbWZpNmxOeTAKAtVgzsPsqcKUntjXcrLVGC4OErE62PAb
            yz58dp1A6RlAYQ+kY65mAw57Yx6U8qOi6EQYt2Q41fMdZNDVUq9DVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T20:09:56Z"
    mac: ENC[AES256_GCM,data:uxMSw4Rj7oCVNpQd3c1Bo8qLZwpue9Lsl/pXeY2+Lde5x24Z9/FfcmBPvOZU9FjfzZKxBvtw6/Xq1LNAtdJGU3dVewXNH6b+8rU8+VFwRDvs0t7W2VdK9Thcq8bs9HZbBdQ2bzC9gNSTBZ2ylGULLnk9Wk+wvkCfOOd/3qH7leY=,iv:LbZ4dqmdUM03e1z8S4YmXC9feA078KVeyyl90WjBjGk=,tag:Znh84NY6iCJ963iWI9Y9qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
